### ISSUE TITLE
Issue with emojis in file name

### ISSUE THREAD

**Issue by twau** [simulot/immich-go#1]
Hi

Some of my photos have weird emojis from an old photo app. This causes immich-go to exit 1:
```
twau@ubuntu:~/Downloads/googletakeout$ ./immich-go -server=http://immich.localdomain:2283 -key=X-google-photos -create-albums ./Takeout
**SNIP**
2744 media scanned
file does not exist
twau@ubuntu:~/Downloads/googletakeout$ echo $?
1
```

File name example:

IMG_MJL_☣️-Sharp-_-Natural-🍀_20201225_15284769.jpg

**Comment by simulot** [comment]
Is it possible to send the json and image files?

**Comment by twau** [comment]
After digging deeper into this and running with the main branch version it seems to be an issue with my google takeout I think.
Photos I deleted that was taken with the app that created filenames with emojies, left behind its json file on Googles end even after being deleted, is my best guess, since I have alot of json files with "title" of an image that dosent exist in the takeout.

**Comment by simulot** [comment]
I have fixed a problem when the archive fits into 2 files. This fix is in release v0.1.2. Have you used that version?

The name of image is truncated (47 char without the extension), specials chars are changed into a _, sometime a space... this makes difficult to find the image after the title. I have no idea how emojis are transformed.
I'll be happy to add the possibility to manage names with emojis.

**Comment by simulot** [comment]
@twau I have improved the way how long file names are handled. in release 0.1.5
Tell me if this work better for you

**Comment by twau** [comment]
Great work! My weird emojies filename no longer get the errors with 0.1.6.

**Comment by simulot** [comment]
I'm glad to close this one!
