### ISSUE TITLE
stack: Huawei Nexus 6P

### ISSUE THREAD

**Issue by krystiancharubin** [simulot/immich-go#100]
Burst
```
00001IMG_00001_BURST20171111030039.jpg
...
00014IMG_00014_BURST20171111030039.jpg
00015IMG_00015_BURST20171111030039_COVER.jpg
```

Regular
```
IMG_20171111_030055.jpg
IMG_20171111_030128.jpg
```

**Comment by simulot** [comment]
This format is weird. 
I'm afraid this format is defeating my date of capture determination based on the photo's name...

**Comment by krystiancharubin** [comment]
Yeah its a little weird since it has the burst count in there twice sort of at the beginning of the filename instead of the end like most other formats. Still the first bit is just the count of the picture in the burst and the remained is just date time components.
Here is a quick regular expression that parses out all the subcomponents.
https://regex101.com/r/50JekN/1

This format is also used on the Google Pixel XL

**Comment by simulot** [comment]
Hi @krystiancharubin 

I'm rewriting the stack program.
I'm wondering if the time in the name of the file is local or UTC?
Could you verify this for me? 
Thanks
