### ISSUE TITLE
duplicated media using takeout archive

### ISSUE THREAD

**Issue by hafx** [simulot/immich-go#110]
Hi, 

I would like to say thank you for the tool. It helped me a lot. 
I've had problems with duplicates.

Fist of all I used the immich client from my phone/tablet/web to upload all assets I had on the storage of these devices. 

Then I used immich-go to upload my Google zip takeout to my immich service with this command : 
```
./immich-go -server=https://url-of-my-immich-service -key=myapikey upload takeout-*.zip
```

After the upload with ```immich-go```  I noticed that there were duplicated media (images and videos).

**Questions** :   
- how can I undo these changes ?  
- Seems the media duplicated have not the same size (low res and high res ?).  
- Is there a parameter to avoid this kind of problem?

I worked a lot of time to import all media  I had of my devices (tablet, computer, smartphone) and I'd like to avoid having to do it all over again. (or deleting manually the low res) 

I though media (images and videos) in takeout archive 'll be compared with the media already uploaded with the immich client. Seems not the case.

```
Immich server :1.91.3
Immich-go : 0.9.4
```

Thanks for your help

**Comment by hafx** [comment]
Oops, I didn't read all the doc. 

I found my answer using : 
```
./immich-go -server=https://url-of-my-immich-services -key=myapikey duplicate -yes
```
Sorry and thank you!

**Comment by hafx** [comment]
Oops, I didn't read all the doc. 

I found my answer using : 
```
./immich-go -server=https://url-of-my-immich-services -key=myapikey duplicate -yes
```
Sorry and thank you!

**Comment by simulot** [comment]
Thanks for your report. 
Be aware how duplicates are detected (and then not always detected):

At immich-go step:
Duplicates detection is based on the file name and the date of capture found in the associated JSON or in the image.
If an image is found on the server with the same name and at the same date, then the respective file size are compared.
If your input file is bigger than the server's file, immich-go remove the server's version and replace it.

At immich server:
Whatever the decision of immich-go, the server take the hash signature of the incoming file, and search if it has already  a file with the same signature. If yes, the server refuses it.

So, if you end up with duplicates in the server, the means the files are slightly different and have different name of date
