### ISSUE TITLE
Unable to import Takeout due to 401 Unauthorized error

### ISSUE THREAD

**Issue by JPT62089** [simulot/immich-go#112]
Howdy! I'm having an issue with immich-go that whenever I run the command to import my Google Takeout (~300 2GB zip files) it errors out right at the start. I've added the log level and file with no luck on getting further logs.

This might be more of an immich issue so please let me know and I can create an issue on that side instead.

I've tried deleting and recreating my API key with no luck and there appears to be no logs on the immich side. I'm trying to run this on my Synology but also tried on my Kubuntu laptop with the same results.

# Version
```
immich-go  0.9.6, commit 1782249564abb77f01780282ca4d8ddaf7ef6f69, built at 2023-12-30T08:30:25Z
immich v1.91.4
```

# Command
`immich-go -server=https://immich.domain.com -key=-key=abcdrealkeyhere upload -create-albums -keep-partner FALSE -log-level INFO -log-file=/tmp/immich-go.log -from-album "Google Takeout" -google-photos /path/to/Takeout/*`

# Error
```
Server status: OK
ValidateConnection, GET, https://immich.domain.com/api/user/me, 401 Unauthorized
Unauthorized
```

**Comment by simulot** [comment]
This error is returned by the server. I suspect an error with the key

**Comment by JPT62089** [comment]
Oh my goodness... Ugh. I am such a derp. `-key=-key=abc`

I think I'll just go back to bed and restart today lol
