### ISSUE TITLE
Duplicated album on media upload.

### ISSUE THREAD

**Issue by magarto** [simulot/immich-go#119]
In last 0.9.7 release, I created a new album name ABCD with no photos/videos in it and later on I use immich-go to upload several linux folders. After uploaded, I can see two ABCD albums with all the videos and photos in both albums.

**Comment by simulot** [comment]
I can't reproduce your problem. Could you share the command line you have used?

**Comment by magarto** [comment]
Something like:

[code]./immich-go -server=http://mynas:2283
-key=zzV6k65KGLNB9mpGeri9n8Jk1VaNGHSCd upload -album "Album" ~/Folder

**Comment by simulot** [comment]
Still not reproduced, sorry

**Comment by simulot** [comment]
Can you run the command again and share the log file produced?
```
./immich-go -server=http://mynas:2283 -key=zzV6k65KGLNB9mpGeri9n8Jk1VaNGHSCd -log-level=INFO -log-file=upload.log upload -album "Album" ~/Folder
```
