### ISSUE TITLE
XMP are rejected

### ISSUE THREAD

**Issue by simulot** [simulot/immich-go#120]
```
immich-go 0.9.7, commit 79eb1be6f49322c2dba080cd86f2c985efc4e46d, built at 2024-01-04T20:41:52Z

Server status: OK
files with extension '.xmp' are not supported. Check the discussion here https://github.com/simulot/immich-go/discussions/109
```

**Comment by jurekl** [comment]
thanks very much!!!
I'll be happy to test it, but probably only tomorrow.
Greetings

P.S.
Taking a very superficial look, there was probably a problem with the double ".xmp" extension in the checkSidecar function :-)
Regards 🥇
