### ISSUE TITLE
Google Photos - shared live photos have bad date data

### ISSUE THREAD

**Issue by GameKing505** [simulot/immich-go#121]
I make use of live photos, which Google Photos seems to handle OK. I used immich-go to import my Google Photos library, and it seems that live photos get broken up into an individual image file (.HEIC or JPEG) and a video file (.mp4 or .mov).

For photos that I have taken myself, Immich is able to group these 2 files together in the interface and I get 1 tile, with a still photo and the ability to click the little play button to view the video component. This is the desired behavior.

For photos that have been shared with me through shared Google albums, Immich displays the image file as separate from the video file. Further, many of the video files appear in the wrong place in the timeline. When I run exiftools on these orphaned video files, I can see that the "Media Create Date" is 0000:00:00 00:00:00, and I assume that Immich's logic for grouping live photos with their video component relies on some sort of timestamp, so perhaps that is causing the issue. This is a bit of a pain, as many of my photos have been shared with me by my wife, resulting in scattered video files inserted at incorrect points in my Immich timeline.

For live photos, is there any way, in the upload process, to alter the exif data for the video files to properly reflect the same timestamp as the corresponding image file?

**Comment by simulot** [comment]
> it seems that live photos get broken up into an individual image file (.HEIC or JPEG) and a video file (.mp4 or .mov).

Correct. Immich-go pass them without special treatment. Immich server recognize them as live photo, but I don't know exactly how. The merge could be based on name, date or an exif ID or any combination. 

> For photos that have been shared with me through shared Google albums, Immich displays the image file as separate from the video file... this is a bit of a pain, as many of my photos have been shared with me by my wife

I have remarked that images shared with me have a lower quality, no exif data like the GPS. I don't know exactly for live photos.

You can do the following test: take a couple of photo/movie and drop them on the immich web page. Do they are recognized as a live photo?


> For live photos, is there any way, in the upload process, to alter the exif data for the video files to properly reflect the same timestamp as the corresponding image file?

I don't know.

**Comment by GameKing505** [comment]
Thanks simulot. I opened up an issue on the immich project [here](https://github.com/immich-app/immich/issues/6201).

If helpful, I've attached an example of a live photo that gets split up into photo/video with different dates in  the immich timeline.

https://github.com/simulot/immich-go/assets/58752730/95500f39-e4f8-4a1c-bab4-bdc7f71663e9

![IMG_2237](https://github.com/simulot/immich-go/assets/58752730/870aa4c2-bbe6-457f-9076-8582d09213de)

**Comment by simulot** [comment]
Nice image! and the live photo make sense here!
I'll check exif data and compare with working sample

**Comment by simulot** [comment]
I did the test. 
I think that pairs of photo / videos are identified by the exif tag `Media Group UUID` for the image and the tag `Content Identifier`

In the files you have shared, the metadata of  the mov have been erased. I don't see how to recover them.

**Comment by GameKing505** [comment]
Thanks for checking on that... 

It's a shame that Google Takeout seems to break that field for images that have been shared from another user. Is there any way to use file name or other fields to recover the link? 

Also separately, I've noticed that if I download locally to my phone from Google, and then upload to Immich, that the linkage between video/image is preserved. Not sure why this would be different from a takeout.

**Comment by GameKing505** [comment]
I guess I'm a bit stuck as far as adopting Immich then... That's a big bummer. And somewhat strange that seemingly no one else moving from Google Photos has run into this issue.

Also just to clarify - I don't think Google Takeout photos are "compressed" as in lower quality. From what I've seen they are the same images, but metadata is messed up.

**Comment by simulot** [comment]
Have you took the live photos with your phone, or are they shared by another user? In the latest case, I know that metadata is striped when shared photos.

>Also just to clarify - I don't think Google Takeout photos are "compressed" as in lower quality. From what I've seen they are the same images, but metadata is messed up.

It depends if you have activated the option to store a compressed version on google drive. In such case immich will duplicate the photos. That duplicates can be removed using immich-go
