### ISSUE TITLE
Duplicate uploads

### ISSUE THREAD

**Issue by Tyoryn** [simulot/immich-go#122]
Having an issue with duplicate images.  I downloaded my photos via takeout and uploaded to immich with immich-go.  Worked great but there's seems to be some conflict between those images and those on my device.  As soon as the immich Mobile app uploads, manually or via automatic upload options, all the photos on my mobile device are uploaded again.  I think it's not catching the duplicates because the file sizes are different for some reason, one nearly double the size of the other.  All the ones coming from mobile appear to append +1 to the end of the file name as well.

**Comment by simulot** [comment]
immich-go should have uploaded photos from the takeout. I guess those one are compressed. The mobile app upload the phone content, where the photos aren't compressed.

The Immich app and the immich server detect duplicates only when files are identical, byte by byte.  The server image is different from the phone image, then the app upload it. This is why you end up with two versions of the photo.

You can use immich-go to remove the duplicates after the phone is completely synchronized with the server. Immich-go  finds duplicates on the server  by using the file name and the date of capture. When date and time matches, immich-go remove the smallest file. Look at the command [duplicate](https://github.com/simulot/immich-go#command-stack).

**Comment by HerzogVonWiesel** [comment]
@simulot That is not the case. I have uploaded only my google takeout and I still have the same issue of two photos for every one with the +1. the one without the "+1" seems to be of higher quality.

**Comment by simulot** [comment]
@HerzogVonWiesel Give a try to the duplicate command
