### ISSUE TITLE
Trying to use your go module

### ISSUE THREAD

**Issue by jaybinks** [simulot/immich-go#123]
on my OSX dev system, im getting this error when doing "go get"
it would be really handly if you could remove the unicode characters from the file paths of your test data.

``
go get github.com/simulot/immich-go@main
go: downloading github.com/simulot/immich-go v0.3.5-0.20240106155015-b864ffd29a10
go: github.com/simulot/immich-go@main: create zip: cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063000139.jpg: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063000139.jpg": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063000139.jpg.json: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063000139.jpg.json": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063029647.jpg: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063029647.jpg": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063029647.jpg.json: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063029647.jpg.json": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063108407.jpg: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063108407.jpg": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063108407.jpg.json: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063108407.jpg.json": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063121958.jpg: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063121958.jpg": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063121958.jpg.json: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063121958.jpg.json": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063357420.jpg: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063357420.jpg": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063357420.jpg.json: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063357420.jpg.json": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063536303.jpg: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063536303.jpg": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063536303.jpg.json: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063536303.jpg.json": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063851485.jpg: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063851485.jpg": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063851485.jpg.json: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063851485.jpg.json": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063909898.LS.mp4: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063909898.LS.mp4": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/PXL_20231006_063909898.LS.mp4.json: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/PXL_20231006_063909898.LS.mp4.json": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout1/Google Photos/Album test 6-10-23/métadonnées.json: malformed file path "cmdupload/TEST_DATA/Takeout1/Google\u00a0Photos/Album test 6-10-23/métadonnées.json": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout2/Google Photos/Photos from 2023/PXL_20231006_063000139.jpg: malformed file path "cmdupload/TEST_DATA/Takeout2/Google\u00a0Photos/Photos from 2023/PXL_20231006_063000139.jpg": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout2/Google Photos/Photos from 2023/PXL_20231006_063000139.jpg.json: malformed file path "cmdupload/TEST_DATA/Takeout2/Google\u00a0Photos/Photos from 2023/PXL_20231006_063000139.jpg.json": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout2/Google Photos/Photos from 2023/PXL_20231006_063528961.jpg: malformed file path "cmdupload/TEST_DATA/Takeout2/Google\u00a0Photos/Photos from 2023/PXL_20231006_063528961.jpg": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout2/Google Photos/Photos from 2023/PXL_20231006_063528961.jpg.json: malformed file path "cmdupload/TEST_DATA/Takeout2/Google\u00a0Photos/Photos from 2023/PXL_20231006_063528961.jpg.json": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout2/Google Photos/Sans titre(9)/PXL_20231006_063108407.jpg: malformed file path "cmdupload/TEST_DATA/Takeout2/Google\u00a0Photos/Sans titre(9)/PXL_20231006_063108407.jpg": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout2/Google Photos/Sans titre(9)/PXL_20231006_063108407.jpg.json: malformed file path "cmdupload/TEST_DATA/Takeout2/Google\u00a0Photos/Sans titre(9)/PXL_20231006_063108407.jpg.json": invalid char '\u00a0'
cmdupload/TEST_DATA/Takeout2/Google Photos/Sans titre(9)/métadonnées.json: malformed file path "cmdupload/TEST_DATA/Takeout2/Google\u00a0Photos/Sans titre(9)/métadonnées.json": invalid char '\u00a0'
``

**Comment by simulot** [comment]
Thanks to reporting this. I didn't know that could makes a problem on Mac OS. The files names with the unicode char are given by  Google in their takeout file. 
Hopefully, the implementation of immich-go doesn't rely on the presence of this name. I'll rename the folders.

I'm curious the know how those files names are converted when unziped on a mac. Let me know what is the standard on mac OS.

**Comment by jaybinks** [comment]
I dont think its a MacOS problem, as I could browse the files after they were downloaded fine.

something in the "go get" toolchain didnt like them.. 
but maybe thats a go on Mac thing ?? I duno
