### ISSUE TITLE
XMP filenames don't always match what is expected

### ISSUE THREAD

**Issue by dlang123** [simulot/immich-go#125]
I have imported thousands of photos over the years onto my discs using various programs, using lightroom a lot.

Usually what happens Is I get three files
image1.jpg
image1.raw (arw lately because of sony)
image1.xmp

From what I can tell and what I see from the output of the immich-go cli import 

```
Scan of the sources:
 21729 files in the input
--------------------------------------------------------
 16371 photos
   391 videos
   305 metadata files
     0 files with metadata
     0 discarded files
   919 files having a type not supported
     0 discarded files because in folder failed videos
 17986 input total (difference 3743)
--------------------------------------------------------
  9080 uploaded files on the server
   142 upgraded files on the server
  7538 files already on the server
     0 discarded files because of options
     2 discarded files because duplicated in the input
     0 discarded files because server has a better image
     0 errors when uploading
 16762 handled total (difference 0)
```

It finds metadata files, but it doesn't seem to associate those together, unless I am just totally misreading this output.  Looking at Immich itself, it seems to think that the sidecar xmp files will be named like : 
image1.jpg.xmp
image1.arw.xmp

Which doesn't seem to be the case for any of the photos from various DSLR's I have imported over the years.  Thoughts?

**Comment by simulot** [comment]
It's a question on immich server behavior

**Comment by simulot** [comment]
I did some tests. immich-server doesn't associate one XMP to both jpg and raw.

I have implemented this behavior in immich-go. See the release note for details.
