### ISSUE TITLE
Parenthesis Name Only Error? 

### ISSUE THREAD

**Issue by sugarfunk** [simulot/immich-go#128]
No sure if this is a fluke or not but trying to track down this issue. Have a takeout with 43 10gb zips so would like to not run this multiple times, but have have very successfully used this script 2 previous times with 2 users. 

After about 26,000 uploads, I start getting errors. Now, the script throws a 400, and sits stagnant for about 20 minutes and eventually tries the next file. Looking at the fees, it seems like each has a common issue in that the entire filename is a parenthesis (see image). 

Checking the immesh logs, I just get "ERROR [AssetService] Unsupported file type .jpg"

So far, I am just waiting to wait out the script because I dont want to have to redo the first 26k, but after 15 hours, this is still going on with about 100 images. 

Would the parenthesis be the issue?  Is the only fix to decompress the 43 files and fix names? I mean that is a huge undertaking I was hoping to avoid. 

![image](https://github.com/simulot/immich-go/assets/1361962/92ee0002-c54d-47c8-b644-f09c88511562)

**Comment by simulot** [comment]
I have seen similar behavior when the filename is weird like `.jpg` 
The error 404 means that `immich-server` has reject the upload request, and all subsequent attempts are rejected has well.

I'll reproduce your case on my system.

**Comment by sugarfunk** [comment]
Just to add to this a bit, since I already had 26k uploaded, I decided to let it continue. It takes 30-45 minutes to 'timeout' and thus move to the next file. I am not at (189).jpg 24 hours later. Cant easily count, but its more that 189, because it has like 001 ,01, 1 variants. wish this would either timeout faster and report failures later or something similar. but script is definitely still running.

**Comment by simulot** [comment]
I did some tests with  my test sytem.

(1).jpg file pass. So by itself it doesn't arm.
I haven't got any delay or timeout.

What is your hardware setup?

**Comment by sugarfunk** [comment]
Running script on Synology 1019+
(64bit, celeron j3455, 16 go ram)
Immich is is running on a Optiplex 7050 sff
(64bit, quad core i5, 16 gb ram)

As I mentioned, this is my third run. Don't know the final library count, but my first run was about 60,000 photos and had no issues. Second was 85,000 with no issues. On my wife's takeout it stopped. 

I'll give it a go again and see if it does it a second time. Got shy to rerun because of how long it took and seemed like a bug but maybe it's my error or a network thing. Seems to much of a coincidence though.

**Comment by sugarfunk** [comment]
Nope. Something still not adding up. Just reran, same error.
<img width="617" alt="image" src="https://github.com/simulot/immich-go/assets/1361962/2fc72aee-8ea7-4e18-ae5f-02c7b505250f">

**Comment by sugarfunk** [comment]
So I decompressed the files and oddly enough, it's the same issue as a ticket you posted to the immich app issues a month ago. I cant find it now but saw it when searching for a solution. Man Google sucks at everything. these files are a mess.
<img width="746" alt="image" src="https://github.com/simulot/immich-go/assets/1361962/b8338e86-3dca-49de-97be-dbc1d20a3e19">

**Comment by simulot** [comment]
The error 400 Bad request is returned by the server. I see in the capture a file `.jpg`. 

There is also and a series of `.jpg(xx).json`. This is the sign that you have several files named `.jpg` on the google photos service. 

I don't know why some of users have bunches of .jpg in there archive. We probably can't change that.

### I think I understand what it happened:

Immich-go read the  json file associated with the image. For the image .jpg, the json is named .jpg.json. The json file file give the original name of the image, here `.jpg`. We know that files named `.jpg` are tripping the immich-server... causing the bad request error. 
 
The next `.jpg` file is stored in the archive as `(1).jpg` to avoid writing over the existing one. Its associated  json is `(1).jpg.json`. This json gives the original file name: `.jpg`. Immich-go upload the image with that name... and this crash the system once again. Doing this several times in a row may crashes all immich-server workers, leading to a timeout, and another cycle starts with the next `.jpg` files.

### So what...

In the light of your report, and what I have got from the issue #88, I think I can circumvent the problem by uploading  `.jpg` files with a legit name , for example 'noname.jpg'.
I'll come back to you after some tests.

**Comment by simulot** [comment]
This is confirmed, and fixed.
Read the release note for details.

**Comment by sugarfunk** [comment]
Confirmed. Amazing. Thank you for so much of your contributions to this community and your patience.
