### ISSUE TITLE
panic: syntax error in pattern

### ISSUE THREAD

**Issue by kaiwei** [simulot/immich-go#131]
Hi, thanks for this wonderful tool. I've been trying to import some old photos but keep running into this error below. Am unsure how to resolve this.

> Server status: OK
> Ask for server's assets...
> 25948 asset(s) received
> Browsing folder(s)...
> Done.
> panic: syntax error in pattern
> 
> goroutine 27 [running]:
> github.com/simulot/immich-go/browser/files.(*LocalAssetBrowser).checkSidecar(0xc000206270, {0x883144?, 0xd?}, 0xc001adc100, {0xc001a80000, 0x15fd, 0x0?}, {0x98a018, 0x1}, {0xc0018d01e0, ...})
>         github.com/simulot/immich-go/browser/files/localassets.go:166 +0x2ba
> github.com/simulot/immich-go/browser/files.(*LocalAssetBrowser).handleFolder(0xc000206270, {0x991620, 0xc000034320}, {0x98db00, 0xc0002322b0}, 0xc0018a56f6?, {0x98a018, 0x1})
>         github.com/simulot/immich-go/browser/files/localassets.go:143 +0x945
> github.com/simulot/immich-go/browser/files.(*LocalAssetBrowser).Browse.func1.1({0x98a018, 0x1}, {0x9917a8, 0xc0018ce440}, {0x0?, 0x0?})
>         github.com/simulot/immich-go/browser/files/localassets.go:52 +0xea
> io/fs.walkDir({0x98db00, 0xc0002322b0}, {0x98a018, 0x1}, {0x9917a8, 0xc0018ce440}, 0xc002383f78)
>         io/fs/walk.go:73 +0x6c
> io/fs.WalkDir({0x98db00, 0xc0002322b0}, {0x98a018, 0x1}, 0xc000092f78)
>         io/fs/walk.go:122 +0xd2
> github.com/simulot/immich-go/browser/files.(*LocalAssetBrowser).Browse.func1({0x991620, 0xc000034320})
>         github.com/simulot/immich-go/browser/files/localassets.go:39 +0x17c
> created by github.com/simulot/immich-go/browser/files.(*LocalAssetBrowser).Browse in goroutine 1
>         github.com/simulot/immich-go/browser/files/localassets.go:36 +0xed

**Comment by simulot** [comment]
Thanks for reporting this. This is indeed unexpected.
I have reproduce the same error with a file named `IMG[a-].HEIC` I guess you have some files of that kind. 

I'm working on a fix

**Comment by kaiwei** [comment]
Working perfectly now. Thanks for the amazingly quick fix!
