### ISSUE TITLE
Google takeout upload failed due to missing json files

### ISSUE THREAD

**Issue by swex** [simulot/immich-go#133]
Hello there!
trying to upload google takeout archive and bunch of error messages like this:
```
Error                    : Takeout/Contacts/All Contacts/9219453021086142833.jpg: JSON File not found for this file
Error                    : Takeout/Contacts/All Contacts/Andrey Shef.jpg: JSON File not found for this file
```
at the end tool said:
```
Managing albums
Scan of the sources:
128543 files in the input
--------------------------------------------------------
 62430 photos
  5962 videos
 51419 metadata files
 49047 files with metadata
  8491 discarded files
   237 files having a type not supported
     4 discarded files because in folder failed videos
128543 input total (difference 0)
--------------------------------------------------------
     0 uploaded files on the server
     0 upgraded files on the server
     0 files already on the server
 41334 discarded files because of options
  7713 discarded files because duplicated in the input
     0 discarded files because server has a better image
     0 errors when uploading
 49047 handled total (difference 19345)
Done.
```
and no upload happened.
I have 2 suggestions:
1. Maybe only search zip archives in Google photos path? eq: `Takeout/Drive/Google Photos` because it looks like currently tool checking all takeout paths for images. (I have full takeout backup with all services, not only Google Photos)
2.  Add an option to skip those errored images paths.

**Comment by simulot** [comment]
Immich-go has never been designed to handle contact takeout.

**Comment by swex** [comment]
I understand that. But it's not contacts takeout, it's all services takeout. Tool `probably` must search only for Google Photos specific paths, no?

**Comment by simulot** [comment]
It wasn't a need so far. I think the import process has continued to the end, am I right?

**Comment by swex** [comment]
no it stops right after error messages, you can see it in result message
```
 0 uploaded files on the server
```

**Comment by simulot** [comment]
At least immich-go should process what it can, and report errors.

**Comment by swex** [comment]
it does processing and reporting errors but not uploading anything. is it planned behavior?

**Comment by simulot** [comment]
Not really. I need to check the code

**Comment by narucx** [comment]
I have the same error but with a lot of videos and photos. Idk if im just doing something wrong here or if those files just arent working

Error                    : Takeout/Google Photos/Photos from 2020/PANO_20200521_163603.vr.jpg: JSON File not found for this file
Error                    : Takeout/Google Photos/Photos from 2020/PANO_20200605_190901.vr.jpg: JSON File not found for this file
Error                    : Takeout/Google Photos/Photos from 2020/VID_20200521_214326.mp4: JSON File not found for this file
Error                    : Takeout/Google Photos/Photos from 2020/VID_20200624_164120.mp4: JSON File not found for this file
Uploaded                 : Takeout/Google Photos/Photos from 2020/VID_20200512_101540.mp4: VID_20200512_101540.mp4
Uploaded                 : Takeout/Google Photos/Photos from 2020/e6bcffd1178861ce50c2c2f755cb7f4b.mp4: e6bcffd1178861ce50c2c2f755cb7f4b.mp4
Managing albums
Scan of the sources:
   687 files in the input
--------------------------------------------------------
   339 photos
    23 videos
   325 metadata files
   108 files with metadata
     0 discarded files
     0 files having a type not supported
     0 discarded files because in folder failed videos
   687 input total (difference 0)
--------------------------------------------------------
   108 uploaded files on the server
     0 upgraded files on the server
     0 files already on the server
     0 discarded files because of options
     0 discarded files because duplicated in the input
     0 discarded files because server has a better image
     0 errors when uploading
   108 handled total (difference 254)
Done.

**Comment by simulot** [comment]
Have you processed all the parts of the takeout archive in the same run? It appears that images are spread across parts

**Comment by narucx** [comment]
Takeout made me download it in 32 different zips
I thought the metadata would be in the same zip as the image/video file itself
but ill try again after adding all files into a single zip

**Comment by simulot** [comment]
Just run immich-go on *.zip

**Comment by narucx** [comment]
![image](https://github.com/simulot/immich-go/assets/75908696/4c424fb8-4f64-4ceb-bfca-896d6564d87b)
yea it was split in 32 different zips

tried them 1 by 1 but that caused issues
added all into one single zip and now i dont have a single error yet

**Comment by simulot** [comment]
As you want. But the simplest way was to do following:
```
./immich-go -server=http://mynas:2283 -key=thekey upload -google-photos   ~/Download/takeout-*.zip             
```

immich-go should open all of them, map the files and start upload.
I haven't tried myself with that many files... I would like to know if this works

**Comment by narucx** [comment]
Ah yea that worked even better and uploaded the remaining files that previously had an error trying to upload them with 1 big folder.
The ä got fucked up during copying ig (nothing to do with imich-go)
![image](https://github.com/simulot/immich-go/assets/75908696/55480cba-fa60-4c41-929b-6880c5263286)

**Comment by simulot** [comment]
hum... I don't like the file names unshch,,refe3.png... 
Could you share the exact names of this files, the associated json and the json content?

**Comment by narucx** [comment]
try with the one big zip file
`immich-go.exe -log-file=logs3.txt -server=http://x.x -key=abc upload -create-albums -google-photos "Google Photos\takeout.zip"`
![image](https://github.com/simulot/immich-go/assets/75908696/289014a2-5c40-4419-995a-bee4a05fd5de)
![image](https://github.com/simulot/immich-go/assets/75908696/03a4bf7d-4df4-4e3c-bcdf-5c33c33b82d7)


try with the takeout-*.zip with the 32 "small" zips
`immich-go.exe -log-file=logs3.txt -server=http://x.x -key=abc upload -create-albums -google-photos "Google Photos\takeout-*.zip"`
![image](https://github.com/simulot/immich-go/assets/75908696/4861ea50-a317-46ec-b933-0c0a17370651)
![image](https://github.com/simulot/immich-go/assets/75908696/43e63fc4-82fc-4b02-87b4-b480002d030e)


I tried both twice (deleted the images first so they'd be uploaded again)
Big zip always fucks up the 'ä' and makes it to ',,'
With the small zip files it doesn't do that
![image](https://github.com/simulot/immich-go/assets/75908696/c2d3eeba-a488-409a-809d-00a03bc03dd1)

**Comment by simulot** [comment]
I think, I got it. For some reasons, the process for making the big file changes the encoding of the file names into something else than UTF-8.

According the zip documentation names in your big zip should be encoded using CP-437 (the one of IBM-PC for 1981!) or not:
``` go
	// NonUTF8 indicates that Name and Comment are not encoded in UTF-8.
        //
	// By specification, the only other encoding permitted should be CP-437,
	// but historically many ZIP readers interpret Name and Comment as whatever
	// the system's local character encoding happens to be.
	//
	// This flag should only be set if the user intends to encode a non-portable
	// ZIP file for a specific localized region. Otherwise, the Writer
	// automatically sets the ZIP format's UTF-8 flag for valid UTF-8 strings.
```
So I'll check how I can reproduce this case, and provide a fix.

Hopefully the zips generated by Google are encoded with UTF-8. So you have completed the upload, right?

**Comment by narucx** [comment]
Yea it worked for most files with the big zip and the rest went through with the small zips
Everything is done for me now ty
