### ISSUE TITLE
Add Support for RAW formats

### ISSUE THREAD

**Issue by jakejones48** [simulot/immich-go#15]
Tried using this to upload my camera files before realising the Nikon RAW files, extension .nef are not uploaded while using this. They are supported with direct upload with the Immich webpage.

I'm sure Canon and other brands also use a different extention. Maybe having a option -file-extention might be useful where it attempts to upload those file extentions, so code changes are not required for each new file extention that Immich supports in the future.

**Comment by simulot** [comment]
I have used the list of extensions supported by the immich-cli tool.
Of course there are DMG, CR2, CR3... 
Let me check what types the server actually supports. 
It's good idea to overcome the default list by an option.

**Comment by simulot** [comment]
Fix merged in v0.2.3
