### ISSUE TITLE
Albums from subdirectories with matching names

### ISSUE THREAD

**Issue by MikeBishop** [simulot/immich-go#159]
I uploaded an existing library of photos with the rough file structure `YEAR/Occasion/Photos.jpg` using the command line ` ~/immich-go -server http://localhost:2283 -key REDACTED upload -create-album-folder=true ./20*`.  Included in that upload were some directories of the form:
![image](https://github.com/simulot/immich-go/assets/4273797/ce8fc62d-fcbf-4228-a4cd-dd1ddc88cf58)

What I would have hoped is to get albums like "2016 Christmas", "2012 Christmas", etc. I thought it more likely to produce multiple albums named "Christmas" and I would then rename them based on the dates of their contents.

What happened instead is that I got one album named "Christmas" which contains Christmas photos from various years, but not every year since not every year had a subfolder called Christmas.

**Comment by simulot** [comment]
I have analyzed your query in details. This wont be possible. The `-create-album-folder=true` option creates albums from the folder name containing the photos. In your case, this is always `Christmas`. 

I don't see how this particular case can be generalized. 

Anyway, I took the opportunity of your issue to simplify the management of command line file arguments;

**Comment by marouamghar** [comment]
That's a bummer, because then you lose all the subdirectories hierarchy. And I don't believe it's a particular case, it's natural to have such a library division

**Comment by simulot** [comment]
Indeed. What do you suggest? How to make it flexible enough to be useful  for any users?

Yo can also rename your directories as you wish name the albums and re-import.

**Comment by MikeBishop** [comment]
I would think that simply taking the list of directory names with some separator (e.g. `2011/Christmas` or `2011 Christmas`) gives enough context to know what the album is expected to contain. If people want to rename further, that can be done after import (or before, as you note).

**Comment by simulot** [comment]
This is simpler than I was thinking

The option -create-album-folder can be smarter:
-create-album-folder or -create-album-folder=folder to have the current behavior
-create-album-folder=path to implement your request

**Comment by giejay** [comment]
@simulot Whats the status of this? Im facing the same "issue", having nested directories with just "3 months old" as the deepest subfolder. It would be great of that could be prepended by the name of our first son, which is a folder up:) 

I tried your -create-album-folder=path but that gives me a boolean parse issue.

**Comment by simulot** [comment]
It's not implemented. 
I haven't  been relaunched on this until now.

**Comment by giejay** [comment]
Ok clear. If you could give me some pointers I'm happy to make a PR. It's just that my experience with Go is quite low but I think it doesn't differ that much from Scala/Java;)

**Comment by simulot** [comment]
That's a nice offer!

Check here: https://github.com/simulot/immich-go/blob/main/cmd/upload/upload.go#L677-L697

**Comment by giejay** [comment]
Here you go: https://github.com/simulot/immich-go/pull/444

I did attempt to go for your approach, using -create-album-folder=path, but somehow, that resolves into "upload -create-album-folder=PathToPhotos" when passing in: "upload -create-album-folder=none PathToPhotos" or "upload -create-album-folder PathToPhotos".

I have no idea why it would do that;)

**Comment by simulot** [comment]
Your solution is good as well.
Thanks

**Comment by simulot** [comment]
That's easy: 
```
GOOS=window go build
```
