### ISSUE TITLE
ignore no metadata error

### ISSUE THREAD

**Issue by np123-glitch** [simulot/immich-go#163]
I have a google takeout archive that I want to upload to immich. everything goes fine except when the tool cannot find the metadata for a specific file it doesn't upload. i have looked through the documentation and cannot find an 'ignore' option. is there a way this feature can be implemented?

**Comment by simulot** [comment]
The unique characteristic of Google Takeout is that files are spread across multiple archive parts. You're likely only handling one part of the archive set at a time. To fix this, you can let Immich-go handle all parts simultaneously. Simply provide Immich-go with the file name pattern "takeout_*.zip".

**Comment by np123-glitch** [comment]
Ah okay thank you very much
