### ISSUE TITLE
[Feature Request:] Set date from file system timestamp

### ISSUE THREAD

**Issue by simonsso** [simulot/immich-go#173]
When uploading ancient files from old forgotten backups where there are no time stamps in the metadata of the files. In those cases I would like to be able to force set the creation time from the timestamp of the files. 

Currently immich thinks now is the correct creation time for such images.

**Comment by simulot** [comment]
The file timestamp can be inaccurate too. In my cases, it the date of the last backup, not the date of the take.

> Currently immich thinks now is the correct creation time for such images.
What do you mean?

**Comment by simonsso** [comment]
When I uploaded some old images yesterday they all appeared on top of the list in immich, as if they were just taken with a camera today.

Even though the file stamp is incorrect, 2015 would be more correct than 2024 for those photos.

**Comment by simulot** [comment]
granted
