### ISSUE TITLE
Immich go failing for most of google takeout assets

### ISSUE THREAD

**Issue by grpursuing** [simulot/immich-go#181]
Trying to upload google take out with Immich go but most of the files are failing with error - JSON file not found for this file. I had 3 takeout files in total and 1 of them successfully got loaded but having this issue with most of the 2nd file. - Any pointers ??

**Comment by coltenkrauter** [comment]
I have 8TB of Google Photos... It is difficult to put them all together... In my case, I would have to purchase a large external hard drive or something like that. Any recommendations for my situation?

**Comment by simulot** [comment]
It's hard to overcome the need of having all files on line to be able to solve the puzzle. 

Another way to do would to fraction the takeout process, by years  for example. Then the size of the the takeout would be manageable.

If you have albums and you want to replicates them, process them by chunk. Don't worry about duplication. Immich-go will detect the album images and will assign them to the album without uploading them another time.

I hope this helps

**Comment by coltenkrauter** [comment]
That's fair... and yes, that helps. I can break up the takeout 👍

Thanks 🙏
