### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by russelltg** [simulot/immich-go#184]
I just realized there is no license file on this project, I suggest adding one so your users know what rights they have to use it. By default, there are none....

For a project like this, GPL-v3 is quite reasonable (disallows distribution of modified binaries without source code)

**Comment by kai-tub** [comment]
Hey, kind reminder to consider adding a license to the repository. :pray: 
If the license allows (and you are fine with it), I would like to add it to the [nix package manager](https://github.com/NixOS/nixpkgs).

**Comment by svenstaro** [comment]
I really wanna stick this into Arch so a license would be great to have on this. Frankly, for this particular tool, you can't really go wrong with any of the popular ones.

**Comment by CommanderRedYT** [comment]
I would like to bump this again, right now the Arch package says "custom license", but does not have a URL to a license because this project does not have one. That's not ideal

**Comment by simulot** [comment]
Closed by #220
