### ISSUE TITLE
[Feature Request] Deduplication while ignoring file extension

### ISSUE THREAD

**Issue by matthewkeller36** [simulot/immich-go#191]
I had previously been backing up my iPhone photos manually on my laptop which has been saving the photos as JPGs (and MOV for live photos). Since I have since deleted some of these photos from my phone, I wanted to merge my Immich account to use photos from both my phone and backup on my laptop.

Using the Immich app on my iPhone uploads photos as HEIC. This means I have duplicate JPGs and MOVs. It would be nice to be able to specify to ignore file extensions when deduplicating as this would allow me to merge the two libraries.

**Comment by simulot** [comment]
Thanks for your PR.
I check it during the week end.
