### ISSUE TITLE
Version 0.13.0 not working as expected

### ISSUE THREAD

**Issue by pedrxd** [simulot/immich-go#199]
For exactly the same command:
> ./immich-go -server=https://example.es/ -key=XXXXX upload -google-photos ../takeout/takeout-20240324T130922Z-001/Takeout/

With version 0.13.0 i am getting this error:
![imagen](https://github.com/simulot/immich-go/assets/8394817/53932815-8ca2-410f-ab72-56eafa00822c)

And with 0.12.0 is working as expected.
![imagen](https://github.com/simulot/immich-go/assets/8394817/9e114a83-59be-4f31-82ba-30ad0da7449b)

**Comment by simulot** [comment]
Confirmed 😕 
I don't have same message though, but I have an error. 

I'll get back to this after by work day
