### ISSUE TITLE
-create-album-folder didn't work

### ISSUE THREAD

**Issue by closewall** [simulot/immich-go#207]
I tried running this by uploading my Nextcloud Photos directory with the -create-album-folder flag, but no albums were created in Immich. My Photos directory in Nextcloud definitely had a collection of folders.

The command I ran (on linux) was
`./immich-go -server http://192.168.1.5:8555 -key kASdgsaHjZBXFD4jkf7gdhfgdb436a65s upload -create-album-folder /mnt/user/nextcloud/mainuser/files/Photos`

(obviously the API key here is not my actual API key)

**Comment by simulot** [comment]
so, `-create-album-folder` is actually working?

**Comment by closewall** [comment]
> so, `-create-album-folder` is actually working?

False alarm.
The import didn't complete the first time and my terminal window disappeared.
I ran the command again. It iterated across all the photos that were already there, then uploaded the remaining photos.
All the albums get created from folders after the upload is complete. No albums got created the first time because the upload command was interrupted.
