### ISSUE TITLE
Deleting or Re-Importing Photos not currently in an album?

### ISSUE THREAD

**Issue by closewall** [simulot/immich-go#208]
Is there a way to do this?
I imported a photo library via directory with the -create-album-folder tag, but I neglected to realize that meant it would create a folder for every single subfolder, and one of the folders contained a huge amount of subfolders with date-based filenamed.

I have since deleted all those albums, but the photos themselves are still in the photo database. I was wondering if there was a way to delete every image that isn't currently assigned to an album so I can re-import them with a better folder structure. Better yet, instead of deleting them, couldn't there be a way to simply re-analyze the directory and recreate the albums according to the new folder structure?

**Comment by simulot** [comment]
I guess you aren't in the google photos case.

> Is there a way to do this? 
> I imported a photo library via directory with the -create-album-folder tag, but I neglected to realize that meant it would create a folder for every single subfolder, and one of the folders contained a huge amount of subfolders with date-based filenamed.
> 

This is the intended behavior

> I have since deleted all those albums, but the photos themselves are still in the photo database. I was wondering if there was a way to delete every image that isn't currently assigned to an album so I can re-import them with a better folder structure. Better yet, instead of deleting them, couldn't there be a way to simply re-analyze the directory and recreate the albums according to the new folder structure?

You can delete photos (and empty the trash) and start over.

It may have a cleaver way: If the photo is already present on the server, it could be possible that immich-go assign the album. I have tested this with the google photo use case, so I'm not sure. Let me know if this work as intended.

**Comment by closewall** [comment]
> I guess you aren't in the google photos case.

Nope.

> This is the intended behavior

I know, it's something I neglected to realize.

> You can delete photos (and empty the trash) and start over.

That would be unfortunate. It's obviously too time-consuming to delete every single photo from these deleted albums from the photos section, so I'd have to delete everything and do a full-reimport? That's another 300GB write to the SSD.

> It may have a cleaver way: If the photo is already present on the server, it could be possible that immich-go assign the album. I have tested this with the google photo use case, so I'm not sure. Let me know if this work as intended.

Can I ask how? Is it just a question of running the same command except with a different folder structure?:

`./immich-go -server http://192.168.1.5:8555 -key kASdgsaHjZBXFD4jkf7gdhfgdb436a65s upload -create-album-folder /mnt/user/nextcloud/mainuser/files/Photos`

**Comment by simulot** [comment]
You can give a try to:

```
./immich-go -server http://192.168.1.5:8555 -key kASdgsaHjZBXFD4jkf7gdhfgdb436a65s upload -album="Paris 2017" /mnt/user/nextcloud/mainuser/files/Photos/2017/Paris
```

The expected behavior is that previously uploaded photos from the folder `mnt/user/nextcloud/mainuser/files/Photos/2017/Paris`   with same name and date, will be added to the album.

**Comment by closewall** [comment]
> You can give a try to:
> 
> ```
> ./immich-go -server http://192.168.1.5:8555 -key kASdgsaHjZBXFD4jkf7gdhfgdb436a65s upload -album="Paris 2017" /mnt/user/nextcloud/mainuser/files/Photos/2017/Paris
> ```
> 
> The expected behavior is that previously uploaded photos from the folder `mnt/user/nextcloud/mainuser/files/Photos/2017/Paris` with same name and date, will be added to the album `Paris 2017`.

Thank you, I will give it a try.

Just extending from this though, is there still no way to delete the files that were originally uploaded from that directory?
Like, what if I decided I didn't want any of those photos from that directory on the current Immich user? And I wanted to bulk delete all of them? I am assuming I would have to delete everything and re-upload properly?

**Comment by simulot** [comment]
> Just extending from this though, is there still no way to delete the files that were originally uploaded from that directory?
Like, what if I decided I didn't want any of those photos from that directory on the current Immich user? And I wanted to bulk delete all of them? I am assuming I would have to delete everything and re-upload properly?

Not at the moment. I'm working currently on a better user interface and better logs. 
I'm still afraid to be responsible of deleting original photos by mistake.
