### ISSUE TITLE
can't find the image with title "___", pattern: "___*.*": file does not exist: "___"

### ISSUE THREAD

**Issue by Deses** [simulot/immich-go#21]
I have several files with this error. I thought it was something to do with tildes or special characters, but there are other files with normal looking filenames, so I can't find a pattern to the error.

Here's a sample of files throwing the error

```
can't find the image with title "0-Cadiz_2005_Romancero.JPG", pattern: "0-Cadiz_2005_Romancero*.*": file does not exist: "Takeout/Google Fotos/España vista a través de mi cámara/0-Cadiz_2005_Romancero.JPG"
can't find the image with title "0-Granada_2007_Alhambra.JPG", pattern: "0-Granada_2007_Alhambra*.*": file does not exist: "Takeout/Google Fotos/España vista a través de mi cámara/0-Granada_2007_Alhambra.JPG"
can't find the image with title "0_Cadiz_2005_Escenarios.JPG", pattern: "0_Cadiz_2005_Escenarios*.*": file does not exist: "Takeout/Google Fotos/España vista a través de mi cámara/0_Cadiz_2005_Escenarios.JPG"
[33mcan't find the image with title "Madrid_2006_Alcala.JPG", pattern: "Madrid_2006_Alcala*.*": file does not exist: "Takeout/Google Fotos/Photos from 2006/Madrid_2006_Alcala.JPG"
[33mcan't find the image with title "Madrid_2006_Fuente.JPG", pattern: "Madrid_2006_Fuente*.*": file does not exist: "Takeout/Google Fotos/Photos from 2006/Madrid_2006_Fuente.JPG"
[33mcan't find the image with title "Oviedo_2006_Catedral.JPG", pattern: "Oviedo_2006_Catedral*.*": file does not exist: "Takeout/Google Fotos/Photos from 2006/Oviedo_2006_Catedral.JPG"
[33mcan't find the image with title "RC_001-0001.jpg", pattern: "RC_001-0001*.*": file does not exist: "Takeout/Google Fotos/Photos from 2010/RC_001-0001.jpg"
[33mcan't find the image with title "RC_001-0002.jpg", pattern: "RC_001-0002*.*": file does not exist: "Takeout/Google Fotos/Photos from 2010/RC_001-0002.jpg"
[33mcan't find the image with title "Reus_2011_Terraza.jpg", pattern: "Reus_2011_Terraza*.*": file does not exist: "Takeout/Google Fotos/Photos from 2011/Reus_2011_Terraza.jpg"
[33mcan't find the image with title "Reus_2011_Torre.jpg", pattern: "Reus_2011_Torre*.*": file does not exist: "Takeout/Google Fotos/Photos from 2011/Reus_2011_Torre.jpg"
[33mcan't find the image with title "Corte 15% comisión.mpg", pattern: "Corte?15%?comisión*.*": file does not exist: "Takeout/Google Fotos/Photos from 2015/Corte?15%?comisión.mpg"
```

There's a bit of everything here. It doesn't seem the all caps extension, special chars or nothing special.

**Comment by simulot** [comment]
This comes from the way google mangles files names in the takeout file. They are using a convoluted way to truncate file names, and for removing some chars like | or / from the names.

You may help me to improve the system by providing some examples of
- the exact name of the json file
- the exact name of the image file
- the content of the json (the title field)

**Comment by Deses** [comment]
I finally had time to take a look at this.

Using this as an example:
```
can't find the image with title "0-Cadiz_2005_Romancero.JPG",
pattern: "0-Cadiz_2005_Romancero*.*": file does not exist:
"Takeout/Google Fotos/España vista a través de mi cámara/0-Cadiz_2005_Romancero.JPG"
```
The json files in `Takeout/Google Fotos/España vista a través de mi cámara/` exist. But the picture is not there.

If I search for `0-Cadiz_2005_Romancero.JPG`, the file is located in `Photos from 2005`.

The content from the json files are **identical** in both locations.:

```JSON
{
  "title": "0-Cadiz_2005_Romancero.JPG",
  "description": "Cádiz.",
  ...
}
```

A solution to "fix" this error would be, assuming that `Photos from` gets uploaded first and then it goes through the Albums, would be to add the photo to the album and trust that the json is right.

Tomorrow I should try doing some exports and remove files from albums. Maybe this is sign that the photo at some point was in the album but was removed from it. I don't think this is the case but I want to cross this possibility.

**Comment by simulot** [comment]
OK, I was assuming that all photos for an album were also present in the album folder...

I have to rethink the way I'm parsing the takeout.

**Comment by simulot** [comment]
I'm still in the middle of code refactoring...

**Comment by Deses** [comment]
Is it taking a lot of work? I hope is not too bad!

**Comment by simulot** [comment]
I think I have understand the root of the problems:

In album's folder, we found generally a metadata.json file with the title of the album, a collection of json files, and images.

- the metadata file name isn't consistent --> fixed
- the album title can be empty --> fixed, in this case, the title will be the folder name (Untitled 1...)
- the image file name can differs from the json name, or from the json content.
- the album is made of all json files, but some of image files can be absent from the folder, but present somewhere else.

The latest implies to re-think my code. This is the normal life of project, no worry.  I just have limited time for it this month.
