### ISSUE TITLE
Clarify discarding due to options

### ISSUE THREAD

**Issue by jtagcat** [simulot/immich-go#210]
```
$ immich-go -server=https://REDACTED -key=REDACTED upload -google-photos Google\ Photos
...
   112 discarded files because of options
...
```

I couldn't find any documentation or place in code where `-exclude-types` or equivalent would be specified. I could probably get the info with verbose logging, but since the docs doesn't cover it:

What was discarded? I didn't specify to exclude manually, may `-google-photos` be the culprit?

**Comment by simulot** [comment]
You should enable log and change the log level to INFO to have the details
```
$ immich-go -server=https://REDACTED -key=REDACTED -log-file=immich-go.log -log-level=INFO upload -google-photos Google\ Photos
```

**Comment by jtagcat** [comment]
Yes, I understand and did. The point here is that generic 'discarded some photos' erodes the feeling of safety / no data loss in migration.

**Comment by simulot** [comment]
Duplicates are reported as duplicates.

**Comment by simulot** [comment]
With the latest version the log file is always produced with INFO level. It contains the reason while files are discarded
