### ISSUE TITLE
Stops at "Ready to upload files"

### ISSUE THREAD

**Issue by StefanWaldraff** [simulot/immich-go#218]
I cannot upload my google takeout to a fresh install of  immich hosted on my unraid server.
I tested with Immich v1.100.0 and v1.101.0 hosted on unraid and Immich-Go 0.12.0 to 0.13.2.
I tried to import from my Windows 10 Deskop and from Unraids bash terminal.
The dry-run option succeeded, the actual run stops at first photo.

Here is the bash output:
root@UnraidNas:/mnt/user/isos/123# ./immich-go -server http://10.10.20.24:8080 -key 2FrQXZZHYIIKluABvCcxJ2LrPbRbBOwsH1Nai1aN3v8 upload -google-photos takeout-20240404T112229Z-001.zip
immich-go  0.13.2, commit 159e3819940075651cd966e6106f1a143bcaa364, built at 2024-04-01T20:53:35Z
Server status: OK
Ask for server's assets...
0 asset(s) received
Browsing google take out archive...
Associating JSON and assets...
Done.
Ready to upload files

Increasing the log-level does not provide any additional output.

Stoping the process gives me:
Ctrl+C received. Shutting down...
Server error             : Takeout/Google Fotos/Donnerstag in Sfakia/IMG_20180524_075655544_HDR.jpg: AssetUpload, POST, http://10.10.20.24:8080/api/asset/upload
Post "http://10.10.20.24:8080/api/asset/upload": context canceled

context canceled

This comment at Spaceinvader Ones how to guide indicates that others have this issue, too.
![grafik](https://github.com/simulot/immich-go/assets/2150419/6180d8ca-4ef0-481a-861b-4cc612b809d8)
 
Please let me know if I can provide any more information.

**Comment by simulot** [comment]
It looks like that upload last forever. 
It may be caused by some network configuration issues. I have seen issues with reverse proxies, OATH configuration...

I'll add a time out on the post queries. At least the program will exit after 30 seconds

**Comment by StefanWaldraff** [comment]
Thanks for looking into this.
I feel like a timout of 30 seconds may be to short for uploading videos with a slow remote connection. Setting a timeout via argument may be a viable solution.

I'm not using OAUTH or a reverse proxy atm and I could upload photos via the web UI. But your hint with the server configuration pointed me in the right direction.
The container logs indicated a connection problem with Redis. I use the internal Redis from Immich but messed up the container name.
After fixing the connection issues it works like a charm! 
Thanks for all your effords and creating this awsome importer solution!

**Comment by simulot** [comment]
Thanks for the report
