### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Darkatek7** [simulot/immich-go#221]
Everytime i run the project it tells me immich-go: command not found:
immich-go -server http://10.0.0.248:2283 -key mykey upload -create-albums -google-photos ./takeout/takeout-*.zip
-bash: immich-go: command not found

my folder
![image](https://github.com/simulot/immich-go/assets/50767771/cad69327-5897-4cc5-ad0f-c254a654e41a)

**Comment by simulot** [comment]
Try with `./` before immich-go command like below
```sh 
./immich-go -server http://10.0.0.248:2283/ -key mykey upload -create-albums -google-photos ./takeout/takeout-*.zip
```

**Comment by simulot** [comment]
Can you take a screen shot?

**Comment by Darkatek7** [comment]
Fixed the issiue bei redecrompressing to tar.gz file
