### ISSUE TITLE
Unable to load photos with Nginx Reverse Proxy

### ISSUE THREAD

**Issue by alansw84** [simulot/immich-go#228]
Hi Developers,

I'm having issue with the web browsing once i have go through nginx reverse proxy. It can load the photos at first, once scroll down further, then it wil become Failed to load assets.
![image](https://github.com/simulot/immich-go/assets/124449374/3b4910fe-484b-494d-a5d4-87b4aad0e2ef)

I have enabled the web socket, but seems still have this issue.

        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://x.x.x.x:2283;
                proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header  X-Forwarded-Proto $scheme;

                # enable websockets: http://nginx.org/en/docs/http/websocket.html
                proxy_http_version 1.1;
                proxy_set_header   Upgrade    $http_upgrade;
                proxy_set_header   Connection "upgrade";

                proxy_read_timeout 600s;
                proxy_send_timeout 600s;
                send_timeout       600s;
        }

**Comment by simulot** [comment]
The screen shots depict the situation when uploading photo in the web APP. You should contact the immich team via discord.

**Comment by alansw84** [comment]
Opps, sorry. Messed up the site
