### ISSUE TITLE
Exclude based on filename / glob?

### ISSUE THREAD

**Issue by markussiebert** [simulot/immich-go#232]
Hi, 
I would like this tool to transfer my fotos from my synology to my selfhosted immich. I want to be able to exclude all SYNOPHOTO.... files, but not related to file type. Is this possible?

**Comment by simulot** [comment]
You can select using glob, but not yet exclude using a glob

On my TODO list.

It may even possible to exclude them by default. 
What would be the exclusion pattern?

**Comment by rechena** [comment]
I have the same request. I would say based on the glob you can exclude anything that is `**/@eaDir/**` and `**/.DS_Store/**`

Thanks

**Comment by simulot** [comment]
closed with 0.20
