### ISSUE TITLE
Partner-taken photos are missing in shared albums

### ISSUE THREAD

**Issue by sidamos** [simulot/immich-go#233]
The option -keep-partner defaults to TRUE, however I it looks like I only have photos that I have taken in the shared albums. The photos that my wife took are missing.

I used these options besides the mandatory one:
-time-zone=Europe/Berlin upload -create-albums -google-photos

**Comment by simulot** [comment]
Partner photos refers to a Google Photos  feature "Share with a contact" that you can find in settings. Those photos are always included into the takeout, and you can exclude them.

Photos shared via albums aren't in the takeout. There isn't way to get them. 
So it's likely that your partner has shared albums.

Anyway, you can ask your partner to takeout her  photos, an import them in immich into here account (with her own API key).

**Comment by sidamos** [comment]
Thanks for the pointer! Will do that.
