### ISSUE TITLE
More verbose logging

### ISSUE THREAD

**Issue by coltenkrauter** [simulot/immich-go#234]
Love this project, it is very helpful.

I am in a position where my Google Takeout is more than 8TB, and each operation that runs is quite slow on my compute. It would be neat to see more logs related to what is going on. For example, I ran the following command, 

```zsh
immich-go -server https://redactedhost -key redacted-xxxxxxx -log-file=./log.txt upload -google-photos ./Takeout
```
And, after running for ~3 hours, I only see the following logs,

```
Server status: OK
Ask for server's assets...
24433 asset(s) received
Browsing google take out archive...
Associating JSON and assets...
Done.
Ready to upload files
```

And it has been sitting on `Ready to upload files` from [this file (googlephotos.go#L410)](https://github.com/simulot/immich-go/blob/674b16534212a02e966d55dbe444ad362a1bea1b/browser/gp/googlephotos.go#L410) for several minutes. I checked a resource monitor and I can see that things are still happening, but it would be neat to have the ability to see more logs, perhaps via a `-debug` or `-verbose` flag.

**Comment by simulot** [comment]
try with  -log-level=INFO

**Comment by coltenkrauter** [comment]
Okay, that makes sense. Thank you!

**Comment by simulot** [comment]
with version 0.14, the log file is always generated with the level INFO.

Either the lean or the fancy user interface are showing the progression
