### ISSUE TITLE
Google Takeout 403 Forbidden on non admin user

### ISSUE THREAD

**Issue by kelter-antunes** [simulot/immich-go#246]
First, thank you for the amazing project!

I'm trying to import my and my wife's Google TakeOuts. My user is the Immich admin, when running immich-go with my API Key (admin) in dry run mode, all goes as expected.
When running with my wife's API Key (non-admin) the Input analysis goes as expected but fails when trying to "upload", and fails with a 403 Forbidden when calling the GetServerStatistics endpoint:

GET, https://SERVER_NAME/api/server-info/statistics

![image](https://github.com/simulot/immich-go/assets/6965808/1be9f42c-392e-489a-87fe-f9b61eccd298)

Running latest version 0.14.0 on Windows. Let me know if you need any more info from my side.

**Comment by simulot** [comment]
Confirmed.
I'm using this call just to display the progression bar. 

Maybe I can replace it by the count of photos / movies checked

**Comment by phdalandan** [comment]
Hi. I am trying to do the same today and also encountering the same exact issue. How do I get this fixed? Thank you!

**Comment by simulot** [comment]
Check the release note
