### ISSUE TITLE
immich-go detects raw and jpg as duplicates

### ISSUE THREAD

**Issue by memehammad** [simulot/immich-go#25]
Hey, trying to run the duplicate detection also detects raw and non raw files as duplicates.
`There are 2 copies of the asset IMG_0826, taken on 0001-01-01T00:00:00Z 
  delete IMG_0826 0x0, 0 B, /photos/upload/73ee8f21-91c6-4c55-b89d-7ccac0740e2b/74d657f3-45f4-492d-81bd-d2df2e309584.JPG
  keep   IMG_0826 0x0, 0 B, /photos/upload/73ee8f21-91c6-4c55-b89d-7ccac0740e2b/3dce3fd6-d5e7-4292-9067-555531f830b2.CR2`
  
  While this would make sense if you're trying to save space many people would probably prefer keeping both because jpgs are easier to work with. 
  It would be great if you could add an option to ignore these kinds of duplicates, since having to manually ignore them takes a huge amount of time with a large library.

**Comment by simulot** [comment]
Indeed. May be this should be the default behavior.
