### ISSUE TITLE
Some photos show with upload date

### ISSUE THREAD

**Issue by Nuuki9** [simulot/immich-go#26]
I've just been uploading the first of several large batches of photos.

Overall it went well, but some of the photos are incorrectly showing up in Immich with today's date. I deleted just those photos, and and re-ran using rhe following command:

```
immich-go -server=<server> -key=<secret> upload -album "An Album" -force-sidecar takeout-*.zip
```

I'm getting the same thing though. Am I doing something wrong?

**Comment by simulot** [comment]
Probably nothing wrong.

My program may contains errors that could indicate a wrong date to the immich server, or the immich server doesn't determine the date correctly what ever immich-go has given.

Can you publish the picture concerned, and the json associated? I'll check my program.

**Comment by Nuuki9** [comment]
No problem. Here's the JSON:

```
{
  "title": "IMG_0254.JPG",
  "description": "",
  "imageViews": "3593",
  "creationTime": {
    "timestamp": "1464552531",
    "formatted": "29 May 2016, 20:08:51 UTC"
  },
  "photoTakenTime": {
    "timestamp": "1461930033",
    "formatted": "29 Apr 2016, 11:40:33 UTC"
  },
  "geoData": {
    "latitude": 0.0,
    "longitude": 0.0,
    "altitude": 0.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  },
  "geoDataExif": {
    "latitude": 0.0,
    "longitude": 0.0,
    "altitude": 0.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  },
  "people": [{
    "name": "REDACTED"
  }],
  "url": "REDACTED",
  "googlePhotosOrigin": {
    "mobileUpload": {
      "deviceType": "IOS_PHONE"
    }
  }
}
```
The date listed there is correct, but its not picking up that date in Immich.

Do you need the image too? I could drag the image here but not sure if that would guive you shat you need?

**Comment by simulot** [comment]
Well, may be the image doesn't have metadata. You can send it by email to limit the diffusion. (jfcassan@gmail.com).
I'll use it to debug my program.

**Comment by Nuuki9** [comment]
I've still not managed to resolve this issue, and if anything I seem to have taken a step back.

Previously, some photos were being uploaded with the upload date as the image creation date, even though there was a sidecar file with the correct date in it. If I deleted those images in Immich and re-ran Immich Go they would be re-created, as expected.

I've now tried again using v0.3.5. The run compltes in about 5 seconds, and shows the following:

```
immich-go  0.3.5, commit 6b4c9454bd2c8a8a0cd65c0aee6ba6a686a97a61, built at 2023-10-14T20:54:19Z
Server status: OK
Connected, user: richard@mines.uk
Get server's assets... 17074 received
Browsing folder(s)...Done.
00000IMG_00000_BURST20200404164213735_COVER-edi.jpg: An asset with the same name:"00000IMG_00000_BURST20200404164213735_COVER-edi", date:"2020-04-04 16:42:13" and size:2.2 MB exists on the server. No need to upload.
2 media scanned...
Update the album Little Man
2 media scanned, 0 uploaded.
Done.
```

Its  a 47Gb Takeout file so its clearly not scanning the whole thing. Am I doing something wrong here?

**Comment by Nuuki9** [comment]
@simulot Any thoughts on this? If I'm doing something wrong that would be ideal, but I'm struggling with what to try next.

**Comment by simulot** [comment]
At the first place, the file  `00000IMG_00000_BURST20200404164213735_COVER-edi.jpg`  has been updated to immich without date. 

Probably because of:
1. The file doesn't have dates in its EXIF data
2. There is no JSON file associated with it

In this case, the only date that make sense is the upload date.
Then, you have relaunched the import. Most of picture were already present in immich. They are ignored. 


But wait. I'm working on an update of the import to handling better such cases. I think that all individual images of the burst are linked to one unique JSON.

Could you send a screen shot of the takeout archive with the names of JSON and the names of the images? Or better send the file list in a text file.

You can DM my on discord @ simulot

**Comment by Nuuki9** [comment]
I just ran it again, as when I last did so it "completed" within a few seconds - way too fast for it to have checked all the files in a 45Gb takeout file.

Having just run it, it has in fact re-uploaded them, which is good. However they're still using today's date. I can provide the full file list if you like, though the file I shared previously is in that batch. That file pair is:

```
IMG_0254.jpg
IMG_0254.jpg.json
```

The contents of that JSON file are as above, but the relevant sections would seem to be:

```
  "creationTime": {
    "timestamp": "1464552531",
    "formatted": "29 May 2016, 20:08:51 UTC"
  },
  "photoTakenTime": {
    "timestamp": "1461930033",
    "formatted": "29 Apr 2016, 11:40:33 UTC"
  }
```
The command I used to try the upload was:

```
immich-go -server=<server> -key=<key>-log-level INFO upload -force-sidecar -album "Little Man" takeout-20231006T130949Z-001.zip
```

If I look at EXIF data there's no create date in there, but as there is a JSON file I assumed it would be picking it up from there.  

If you still want the full file list let me know, but as its only a subset affected I wasn't sure if that was going to be helpful, or if focussing on this known problem file would be easier. Let me know.

**Comment by simulot** [comment]
> If I look at EXIF data there's no create date in there, but as there is a JSON file I assumed it would be picking it up from there.

If the file was existing in immich prior this, immich won't accept the file nor its metadata.
Unfortunately there isn't any api to update the date or any other meta information.

I think this limitation is linked to the fact that the image is in a folder named after the date of capture.
I have read they are think about a better storage design that would enable to change the date... Keep finger crossed 

The only way would be to remove the file from immich, and re-upload it with the sidecar file...  May I'll implement this contraption if the feature won't come soon.

**Comment by Nuuki9** [comment]
> If the file was existing in immich prior this, immich won't accept the file nor its metadata.
> Unfortunately there isn't any api to update the date or any other meta information.

Can you clarify what you mean? The image was previously uploaded via Immich Go and had the same upload date issue. Are you saying that even though I then deleted it in Immich, (and uploaded again) that its still "in" there? If so I assume you mean in the database, as its not on the filesystem. 

If that's the case, I could go into the database and clear out the entry, but it seems odd that deleting it from within the Immich UI would leave an orphaned database entry, so wanted to check if that's what you were saying?

**Comment by simulot** [comment]
> Can you clarify what you mean? The image was previously uploaded via Immich Go and had the same upload date issue.
Are you saying that even though I then deleted it in Immich, (and uploaded again) that its still "in" there? If so I assume you mean in the database, as its not on the filesystem.

Deleting the file in immich cleans the database and delete the file. So, when the file is processed by immich-go, it will be uploaded.  With the flag `-google-photos`, the json file associated with the image is used to give the the date.

Let me know if the the date is still incorrect after that.

**Comment by Nuuki9** [comment]
Ah - so does the JSON file _only_ get used when you use the `-google-photos` flag, even if you use `-force-sidecar` flag? If so that might explain it - I wanted to upload the photos into an existing Immich album, which is why I used the switches I did, but if that's not possible I could work around it I'm sure.

**Comment by simulot** [comment]
Yes, force-sidecar works only with Google photos mode.

Otherwise it try using exif data, that are missing for this file

**Comment by Nuuki9** [comment]
Ah right understood - that would explain it. If I re-upload using the following command, will it put the photos into the existing Immich album:

```
immich-go -server=<server> -key=<secret> upload -google-photos -album "An Album" *.zip
```

Wasn't sure if I need to explicitly exclude the `-create-albums` flag, or if including `-album` will superceed that? If I _have_ to recreate the Google Photos Album then I can probably just do that and then moved them within Immich, but ideal to drop them directly into the right (new) album.

**Comment by Nuuki9** [comment]
I tried that command above and the problem files uploaded into the Immich album with the correct date. Apologies for any confusion on my part, and many thanks for the great tool!

**Comment by simulot** [comment]
Not a problem. I could also write a better documentation too.

>any thanks for the great tool!

You're welcome. Give it a star and promote it.

**Comment by Nuuki9** [comment]
Will do! :-)
