### ISSUE TITLE
Should scanned image + scanned video = total uploaded files?

### ISSUE THREAD

**Issue by qodesmith** [simulot/immich-go#267]
I have (10) 50GB zip files from google takeout. I'm going one by one. Here's an example output for the 2nd file:

```
Input analysis:
----------------------
scanned image file                      :    6320
scanned video file                      :    1492
scanned sidecar file                    :    2610
discarded file                          :      12
unsupported file                        :       0
file duplicated in the input            :       0
associated metadata file                :    2751
missing associated metadata file        :       0

Uploading:
----------
uploaded                                :    2280
server error                            :       0
file not selected                       :      60
server's asset upgraded with the input  :       0
server has same photo                   :     408
server has a better asset               :       0
```

If it scanned `6320` images and `1492` videos, why do I only see `2280` uploads? Shouldn't I see a total of `7812`?

**Comment by simulot** [comment]
It's looks like you have processed only one part of the takeout files... and the "missing associated metadata file" isn't correct here.

The maths are:

uploaded = scanned image file + scanned video file - discarded file - unsupported file - file not selected  - server has same photo - server has a better asset  So 7332.

**Comment by qodesmith** [comment]
Should I instead try to process _all_ the zip files at once like this?

```
immich-go -server <my sercer> -key <api kye> upload -google-photos /path/to/google/zipfiles/*.zip
```

Will that prevent any missing data?

**Comment by simulot** [comment]
Correct

Google photos takeout is a mess... Metadata files can be stored in another zip than the photo.

I'm fixing the `missing associated metadata file` counter
