### ISSUE TITLE
Wrong release downloaded for 0.15.0

### ISSUE THREAD

**Issue by chk86** [simulot/immich-go#272]
Hello, 
I just downloaded the  immich-go_Linux_x86_64.tar from release 0.15.0 and when I go to run the command it's showing me: 
``` immich-go  0.13.2, commit 159e3819940075651cd966e6106f1a143bcaa364, built at 2024-04-01T20:53:35Z ```
Shouldn't it say 0.15.0? 
Thanks!

**Comment by chk86** [comment]
I just downloaded 0.14.1 and it seems to be correct:
```rocinante86@Rocinante86:/volume1/gphotos-sync/Cameron_Wedding$ ./immich-go
immich-go  0.14.1, commit f8e7b42b29cdae75be69afe2181dfc58b58cc674, built at 2024-05-20T13:44:20Z
. _ _  _ _ . _|_     _  _ 
|| | || | ||(_| | ─ (_|(_)
            v 0.14.1 _)   
```

**Comment by simulot** [comment]
OOps, confirmed.
