### ISSUE TITLE
Motion photo is shown on Android as motion photo AND a video

### ISSUE THREAD

**Issue by andrej-zirko** [simulot/immich-go#280]
I imported motion photos from Google Takeout via immich-go. The motion photos are displayed properly on the web version of Immich. However, on the Android app, each motion photo is shown as both a motion photo and a video without a thumbnail. The video displays an exclamation point instead of a thumbnail, and its playback is stuttering.

Command used for import
`./immich-go -server http://xxx:2283 -key XXX upload -create-albums -google-photos takeout-20240529T131543Z-001.zip`

Attached sample takeout
[takeout-20240529T131543Z-001.zip](https://github.com/user-attachments/files/15525135/takeout-20240529T131543Z-001.zip)

Originally, I opened the issue on https://github.com/immich-app/immich/issues/9790.

immich-go  0.16.0, commit 7579f2577f5f24c1e6d3b266989112777332e868, built at 2024-06-02T09:25:25Z

**Comment by simulot** [comment]
The common file names for a live photo on Android are PHOTO.JPG and PHOTO.MP The .MP are just discarded.

Your smartphone names the video with the extension .MP4.  
I need to find an accurate way to detect this case and upload only the photo

**Comment by andrej-zirko** [comment]
[takeout-20240611T122312Z-001.zip](https://github.com/user-attachments/files/15883156/takeout-20240611T122312Z-001.zip)

I added one regular video (not a motion photo). The video accompanying the motion photo shares the same filename as the jpg, but it doesn't have a metadata JSON file. Conversely, the regular video does have a metadata JSON file. There doesn't appear to be any other information in the takeout to differentiate between the motion video and the regular video.

**Comment by simulot** [comment]
Thanks
That confirms my thoughts.
I need to refactor the code

**Comment by m1ndy** [comment]
Samsung, Apple and Google (Pixel) are the three motion/live photo+video formats we need to support correctly for a smooth Photos import experience. 

Especially since Live and Motion photos are now the default ON on Galaxy, Z, Pixel and iPhone series of phones in recent years.
