### ISSUE TITLE
Very long time to upload the entire photos directory

### ISSUE THREAD

**Issue by pkking** [simulot/immich-go#290]
At first, thanks this awesome project!

Im a newbie for immich, and i tried to upload all my photos into immich using `immich-go upload <my dir path>` and want to keep them up-to-date, the first upload process take a very long time.

Im wondering if this is the expect use case for `immich-go` by **installing the command into cronjob every day**, will it still cost the same long time next round?

**Comment by simulot** [comment]
immich-go download the complete list of immich's photos to detect if a file need to be upload. This takes a while with big collections. 

The version 0.16 fixes a bug that was causing to upload the file even when it was already uploaded. Be sure of using it.
Why not try the "library" functionality? It does the work from the point of view of the server.
I plan to change the strategy. I'll check the duplicate for each files at the cost of a server call for each file.

**Comment by pkking** [comment]
> immich-go download the complete list of immich's photos to detect if a file need to be upload. This takes a while with big collections.
> 
> The version 0.16 fixes a bug that was causing to upload the file even when it was already uploaded. Be sure of using it. Why not try the "library" functionality? It does the work from the point of view of the server. I plan to change the strategy. I'll check the duplicate for each files at the cost of a server call for each file.

Thanks the reply:), i do notice the `external library` feature after uploading all my photos 😄, so im not sure is it a good idea to add all photos directory as `external library`, will it double all the photos?

**Comment by simulot** [comment]
> Thanks the reply:), i do notice the `external library` feature after uploading all my photos 😄, so im not sure is it a good idea to add all photos directory as `external library`, will it double all the photos?

Probably yes.
