### ISSUE TITLE
ValidateConnection fails after update to Immich server v1.106

### ISSUE THREAD

**Issue by blackmyre** [simulot/immich-go#295]
Attempts to use immich-go failing after updating immich from v1.105 to v1.106.
Log shows:
INFO | Server status: OK | time="2024-06-12T06:51.57 BST"
INFO | ValidateConnection, GET, https://my-immich-url/api/user/me, 404 Not Found

immich-go  0.16.0, commit 7579f2577f5f24c1e6d3b266989112777332e868, built at 2024-06-02T09:25:25Z
immich server v1.106.2

Was previously working as expected against v1.105

**Comment by simulot** [comment]
You have to used the 0.17 version of immich-go.
