### ISSUE TITLE
[FEATURE REQUEST] Derive Immich album description and location from Google photos JSON "enrichments"

### ISSUE THREAD

**Issue by chrisscotland** [simulot/immich-go#297]
This is an incredibly useful tool already but one feature that would be nice to have would be the ability to add additional metadata to Immich albums on import from Google photos.

Using the google photos android app you can add description text to albums. This feature does not seem to be available from google photos on the web. This text also does not appear in the takeout JSON files from what I can see and therefore there is no way to import it.

Using google photos on the web you can add (multiple) text fields into albums. These are listed as 'enrichments' in the album metadata.json. Other enrichments can be added such as an album location (again there can potentially be multiple).

I use these fields to add a description to an album and also a location where the original photos were not geotagged. Would it be possible to parse these JSON enrichments when importing an album to Immich (via a command line option?). For my use case all the text enrichments should be concatenated and added to the Immich album description. If a single location enrichment exists, and the photos have no geotag themselves, the album enrichment location should be added to the photos.

Attached screenshots show an album on google photos app, google photos web and after import to Immich. The relevant album takeout also attached.

![Screenshot_20240613-104243](https://github.com/simulot/immich-go/assets/142149847/0f3cf6cc-4689-4cd0-9125-317393276b31)
![google album with text](https://github.com/simulot/immich-go/assets/142149847/031dac38-60bb-4cbd-8d91-ee334c938fe8)
![immich album](https://github.com/simulot/immich-go/assets/142149847/599a981a-18d8-45f0-8512-d170715e45f0)

[takeout-20240613T094535Z-001.zip](https://github.com/user-attachments/files/15817530/takeout-20240613T094535Z-001.zip)

**Comment by simulot** [comment]
Good Idea
Thank you of having documented your request.

I like the idea of using the album's coordinates to set Photo's coordinates.
This would requiers to refactor the way of handling albums.

**Comment by chrisscotland** [comment]
Thanks so much for the time you've put into this already, it's a great tool and works really well. I feel it will become more and more important as Immich moves towards a stable release and hopefully attracts more users wishing to take ownership back from Google.

**Comment by simulot** [comment]
This will end up in the next release:

![v0 19 Album description](https://github.com/simulot/immich-go/assets/5980377/fd0217be-1f6f-4bd0-91eb-afa6a7aef77a)

And all photos get the album location

**Comment by chrisscotland** [comment]
Thank you so much, can't wait to test it
