### ISSUE TITLE
Google photos import: Handling of edited (rotated) photos

### ISSUE THREAD

**Issue by chrisscotland** [simulot/immich-go#298]
I have an album of photos on google photos where some of the raw photos had the wrong orientation. I corrected the orientation in google photos and on google photos I have only 1 copy of the photo in my library and it shows the correct orientation.

In the takeout archive there is a "XXXXX-edited" version of the file which displays the correct orientation alongside the original file. There was only 1 json file present for the original unedited photo but immich-go successfully associated the edited photo with this json. Both the unedited and edited photos were then uploaded to Immich and are present in the album as duplicates (one with wrong orientation).

Would it be possible to add an option to not import original photos where an edited copy exists? This would avoid these duplicates in my collection.

![immich album](https://github.com/simulot/immich-go/assets/142149847/77364566-cd6a-4feb-b4f2-539e6f1c0077)

Example takeout archive & log file attached.
[takeout-20240613T094535Z-001.zip](https://github.com/user-attachments/files/15817771/takeout-20240613T094535Z-001.zip)
[immich-go_2024-06-13_10-49-40.log](https://github.com/user-attachments/files/15817798/immich-go_2024-06-13_10-49-40.log)

**Comment by simulot** [comment]
Nice suggestion.

The "-edited"  depend on the phone maker and the user language.

**Comment by m1ndy** [comment]
+1 to this.

**Comment by simulot** [comment]
What if you have edited your image several times?
What if you regret the change you have made?

Maybe the best is to let the user decide which version to keep.
