### ISSUE TITLE
Real time GUI log only shows 4 lines 

### ISSUE THREAD

**Issue by dzg** [simulot/immich-go#299]
<img width="1306" alt="image" src="https://github.com/simulot/immich-go/assets/466557/17fcc1c4-2ae9-4ba1-a1b4-1e682387de9e">

It flashes a windowful of lines for an instant, but then just shows 4 lines. Regardless of size of window.

Amazing tool, thank you!

**Comment by simulot** [comment]
>  It flashes a windowful of lines for an instant, but then just shows 4 lines. Regardless of size of window.

I have noticed. Thanks for reporting it

> Amazing tool, thank you!

U're welcome
