### ISSUE TITLE
Error when uploading images with a wild card without path *.JPG 

### ISSUE THREAD

**Issue by Jab2870** [simulot/immich-go#304]
Hi,

Thanks for making this tool. I have an issue where I am trying to upload a bunch of photos 

```
immich-go -no-ui -server=https://photos.my.domain -key=my-key upload --album "Album Name" *.JPG
```

This appears to work, however, only 5 of the images are uploaded.

Here is the output from the logfile:

```
...
 INFO | error | !BADKEY="stat .: os: DirFS with empty root" time="2024-06-16T10:18.26 BST"
 INFO | error | !BADKEY="stat .: os: DirFS with empty root" time="2024-06-16T10:18.26 BST"
 INFO | error | !BADKEY="stat .: os: DirFS with empty root" time="2024-06-16T10:18.26 BST"
 INFO | error | !BADKEY="stat .: os: DirFS with empty root" time="2024-06-16T10:18.26 BST"
 INFO | error | !BADKEY="stat .: os: DirFS with empty root" time="2024-06-16T10:18.26 BST"
 INFO | error | !BADKEY="stat .: os: DirFS with empty root" time="2024-06-16T10:18.26 BST"
 INFO | error | !BADKEY="stat .: os: DirFS with empty root" time="2024-06-16T10:18.26 BST"
 INFO | error | !BADKEY="stat .: os: DirFS with empty root" time="2024-06-16T10:18.26 BST"
 INFO | scanned image file | file=IMG_20180707_070116559.jpg time="2024-06-16T10:18.26 BST"
 INFO | scanned image file | file=IMG_20180707_140252544.jpg time="2024-06-16T10:18.26 BST"
...
```

The files that don't get uploaded are obviously the ones that are erroring.

#259 is about the tool not reporting errors - which I think is either still an issue or may have been an issue. I only spotted this because I knew there were a lot more than 5 photos in the folder, and the tool outputted that 5 had been uploaded.

I don't know what is causing the stat error, although each of the files can be "stat-ed"
![image](https://github.com/simulot/immich-go/assets/1909202/601fd8d8-d237-4dea-9963-19d97c71b986)

**Comment by simulot** [comment]
I can't reproduce your case. 

Are files located on a remote system?
Could you share the content to the folder you try to upload?

BTW, the options have only one dash:  `-album, but this isn't the problem here.
#259 concerns discarded files not well identified into the logs

**Comment by Jab2870** [comment]
I will email you an example file that I am struggling with. I'd prefer it not to be on a public issue

**Comment by simulot** [comment]
You can use my discord handle @simulot as well

**Comment by Jab2870** [comment]
I have send you an email with an example image that is not uploading. 

> Are files located on a remote system?

Not as far as immich-go is concerned. I am ssh'd into my nas and running immich go from there. Both immich go and the the photo are on the system I'm SSH'd into.

> BTW, the options have only one dash: `-album, but this isn't the problem here.

Mussel memory there. Interestingly double dash did create the folder

**Comment by simulot** [comment]
The work around is:
```
immich-go -no-ui -server=https://photos.my.domain -key=my-key upload --album "Album Name" ./*.JPG
```

**Comment by Jab2870** [comment]
Can confirm that works - although i get the same behaviour regardless of the location of the binary.
