### ISSUE TITLE
Timezone error on 0.3.2

### ISSUE THREAD

**Issue by Nuuki9** [simulot/immich-go#31]
I've tried doing an upload using 0.3.2 and I'm getting the following error:

```
immich-go  0.3.2, commit 8d36fff067d39347be9e01706c4b4b78a36d8245, built at 2023-10-10T20:29:36Z
Server status: OK
Connected, user: <username>
Get server's assets...GetAllAssets, GET, http://<server>/api/asset, 200 OK
unknown time zone Europe/London
unknown time zone Europe/London
```

I was using the same command as #26, as I was testing if the new versions had resolved the problem I was getting.

**Comment by simulot** [comment]
Its the same as #30 

I try to understand why a windows machine doesn't know the the time zone Europe/London nor Europe/Paris....

**Comment by Nuuki9** [comment]
Apologies - I'll monito that Issue inatead... Thanks!
