### ISSUE TITLE
SYNOFILE_THUMB_{some pattern}.jpg should be automatically skipped from being uploaded

### ISSUE THREAD

**Issue by erkexzcx** [simulot/immich-go#319]
# Issue

Images (or videos, I don't know) uploaded to Synology NAS sometimes have low quality pictures, such as `SYNOFILE_THUMB_M.jpg`. Anything that starts with `SYNOFILE_THUMB_` should be excluded from uploading by immich-go.

Such uploaded "thumbs" will be considered as actual photos with a totally invalid timestamp. On top of that, Immich's (not immich-go) deduplication does not see them as duplicates.

# Alternative workaround

Search for such photos and manually delete them:
![image](https://github.com/simulot/immich-go/assets/5955795/f58662c5-9190-4d8c-996b-94f0039cf686)

**Comment by erkexzcx** [comment]
Someone created a Reddit post about it too. https://www.reddit.com/r/immich/comments/18r7cxt/delete_photos_by_filename/

**Comment by simulot** [comment]
Thanks... 
I'm not aware of this.
