### ISSUE TITLE
Creation timestamp from metadata is wrong

### ISSUE THREAD

**Issue by Dr3nz4r** [simulot/immich-go#332]
Imported some files and the time in immich is completely wrong.

I am running immich-go.exe on windows 11 with english as the OS language. Ran with these parameters:
```
.\immich-go.exe `
  -server=https://XYZ `
  -key=XYZ `
  upload `
  -create-albums `
  -google-photos `
  S:\GPhotos
```

Here's the metadata from the json (blanked the google url)

```json
{
  "title": "VID_20160822_093541.mp4",
  "description": "",
  "imageViews": "14",
  "creationTime": {
    "timestamp": "1480019341",
    "formatted": "24.11.2016, 20:29:01 UTC"
  },
  "photoTakenTime": {
    "timestamp": "1471851354",
    "formatted": "22.08.2016, 07:35:54 UTC"
  },
  "geoData": {
    "latitude": 0.0,
    "longitude": 0.0,
    "altitude": 0.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  },
  "geoDataExif": {
    "latitude": 0.0,
    "longitude": 0.0,
    "altitude": 0.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  },
  "url": "https://photos.google.com/photo/*****",
  "googlePhotosOrigin": {
    "mobileUpload": {
      "deviceFolder": {
        "localFolderName": ""
      },
      "deviceType": "ANDROID_PHONE"
    }
  }
}
```

here's the result in immich:
![image](https://github.com/simulot/immich-go/assets/75803461/fad9ddf6-db36-4ed7-9640-d9bc9693c30a)

pretty sure this wasn't taken in the year 221014 🥲

**Comment by simulot** [comment]
Look at exif data. Immich just passes the file to the server.

**Comment by Dr3nz4r** [comment]
Sorry total noob here, what is exif data?

**Comment by Dr3nz4r** [comment]
> Sorry total noob here, what is exif data?

Found some online tool it lists in an example file:

CreateDate	2036-01-01 23:59:59 +0000
MediaCreateDate	2018-10-14 23:52:42 +0000
HandlerDescription	ISO Media file produced by Google Inc. Created on: 10/14/2018.

Note: at first glance all affected files seem to be videos (mp4)

**Comment by simulot** [comment]
Some MP4 are stored in google photos with a wrong date. I have a couple of files affected as well.

Immich server can't use the JSON file, and apparently ignore the date that Immich-go gives.
There is nothing that immich-go can do

**Comment by Dr3nz4r** [comment]
> Some MP4 are stored in google photos with a wrong date. I have a couple of files affected as well.
> 
> Immich server can't use the JSON file, and apparently ignore the date that Immich-go gives. There is nothing that immich-go can do

Bummer, the date in Google photos is correct though. Guess an issue with immich needs to be opened then. Thx!
