### ISSUE TITLE
Processing stops with "context canceled" all the time

### ISSUE THREAD

**Issue by CloneXpert** [simulot/immich-go#336]
Tried uploading in multiple ways, different albums, but none of them I could get to work.

The input analysis works as expected, but it always abruptly stops at Immich content progress bar around 60% with 

`INFO | 
Input analysis:
---------------
scanned image file                      :     340
scanned video file                      :     144
scanned sidecar file                    :     502
discarded file                          :       0
unsupported file                        :       0
file duplicated in the input            :       0
associated metadata file                :      17
missing associated metadata file        :       0

Uploading:
----------
uploaded                                :       0
upload error                            :       0
file not selected                       :       0
server's asset upgraded with the input  :       0
server has same asset                   :       0
server has a better asset               :       0
 | time="2024-06-30T11:47.53 CEST"
 INFO | context canceled | time="2024-06-30T11:47.53 CEST"

There's no more detail to understand what's failing. Any ideas to troubleshoot this?

I'm running currently latest v0.18 on win64. The content is already uploaded on the server (external library) but without the metadata extraction - don't know if this could be relevant.

Also, there's no waiting, it runs through like a breeze and I'm connecting to the localhost address (though I also have a public domain registered for it).

**Comment by simulot** [comment]
Gosh, I haven't tested the windows binaries... Let me check

**Comment by simulot** [comment]
Checked, it's work with Windows 11, latest release of immich.

What is the command line?

**Comment by adamssecretcode** [comment]
I had the same problem on linux x64 with 0.18. It would go through a percentage of my photos (scanning), then say "context cancelled". However, importing works as expected on 0.17. Here's what I ran: 

`./immich-go` -server=http://URL:PORT -key=KEY upload -google-photos  "/mnt/user/Share/Takeout/Google Photos"

**Comment by simulot** [comment]
Sorry, all is working on my mint box.
What the log says?

**Comment by tictocdoc** [comment]
Having the same issue on a Win 11 box.  Here is my log file:
 INFO | Connection to the server http://192.168.1.228:2283 | time="2024-06-30T12:56.03 CDT"
 INFO | Server status: OK | time="2024-06-30T12:56.03 CDT"
 INFO | Connected, user: m***********2@gmail.com | time="2024-06-30T12:56.03 CDT"
 INFO | Browsing google take out archive... | time="2024-06-30T12:56.03 CDT"
 INFO | scanned image file | file="Takeout/Google Photos/.308 Rem Model 783/0702202350_Film4.jpg" time="2024-06-30T12:56.03 CDT"
 INFO | scanned sidecar file | file="Takeout/Google Photos/.308 Rem Model 783/0702202350_Film4.jpg.json" type="asset metadata" title=0702202350_Film4.jpg time="2024-06-30T12:56.03 CDT"
 INFO | scanned image file | file="Takeout/Google Photos/.308 Rem Model 783/0702202350a_Film4.jpg" time="2024-06-30T12:56.03 CDT"
 INFO | scanned sidecar file | file="Takeout/Google Photos/.308 Rem Model 783/0702202350a_Film4.jpg.json" type="asset metadata" title=0702202350a_Film4.jpg time="2024-06-30T12:56.03 CDT"
 ...............
  INFO | associated metadata file | file="Takeout\\Google Photos\\Photos from 2010\\Gribelin072.jpg" json=Gribelin072.jpg.json year=2010 size=151919 matcher=normalMatch time="2024-06-30T12:56.13 CDT"
 INFO | associated metadata file | file="Takeout\\Google Photos\\Photos from 2010\\Gribelin073.jpg" json=Gribelin073.jpg.json year=2010 size=170794 matcher=normalMatch time="2024-06-30T12:56.13 CDT"
 INFO | associated metadata file | file="Takeout\\Google Photos\\Photos from 2010\\Gribelin074.jpg" json=Gribelin074.jpg.json year=2010 size=122716 matcher=normalMatch time="2024-06-30T12:56.13 CDT"
 INFO | associated metadata file | file="Takeout\\Google Photos\\Photos from 2010\\Gribelin075.jpg" json=Gribelin075.jpg.json year=2010 size=228318 matcher=normalMatch time="2024-06-30T12:56.13 CDT"
 INFO | 
Input analysis:
---------------
scanned image file                      :   71856
scanned video file                      :     718
scanned sidecar file                    :   74453
discarded file                          :       8
unsupported file                        :      21
file duplicated in the input            :       0
associated metadata file                :   26870
missing associated metadata file        :       0

Uploading:
----------
uploaded                                :       0
upload error                            :       0
file not selected                       :       0
server's asset upgraded with the input  :       0
server has same asset                   :       0
server has a better asset               :       0
 | time="2024-06-30T12:56.13 CDT"
 INFO | context canceled | time="2024-06-30T12:56.13 CDT"

**Comment by simulot** [comment]
At the same I have got several report telling it works ...

@tictocdoc  report shows only  26870 files associated with a JSON over 72574 photos + videos.
either the program has crashed while associating JSON to files or you have processed only on file of the multi files archive. Could you confirm?

**Comment by simulot** [comment]
@CloneXpert , @tictocdoc , @adamssecretcode 
Does the program stops around 10 secondes after its start?

**Comment by kennym** [comment]
same error here!

**Comment by kennym** [comment]
Just pulled latest `main` and https://github.com/simulot/immich-go/commit/472a51ae3a1467f14c0d9f82fb3b402532d6b42c seems to fix that. Thanks

**Comment by CloneXpert** [comment]
I can also confirm it works now, thanks for the quick turnaround.
