### ISSUE TITLE
An option to use file modification time vice creation time for image age upload.

### ISSUE THREAD

**Issue by IMarvinTPA** [simulot/immich-go#339]
I copied files from a dying drive without preserving the creation time cp -p...  So, all of the files have the time I copied them, not the time they were created for their created/birth timestamp.  The last modified time is close enough that I want to use that.

I need -when-no-date=FILE|NOW to have a third option such as FILEMOD which uses the file's modification time instead of its creation/birth timestamp.

I cannot force the modification timestamp over the creation time in linux because linux tools are designed to not allow modifying the creation time.

I cannot recopy the files since they are on a drive that does not play well.

**Comment by IMarvinTPA** [comment]
Or I was misreading things in the log:

> INFO | uploaded | file="xyz.jpg" "capture date"="2000-06-27 09:56:06 -0400 EDT" time="2024-06-30T07:06.58 EDT"

time= is what I was reading as the time being sent for the file, but not all entries have the "capture date" part.   Perhaps time should be "uploading time" or something to indicate that it is related to the time the upload action is occurring.

**Comment by simulot** [comment]
That is how the log system write the timestamp... I don't know why the timestamp is placed at the line end
