### ISSUE TITLE
0.18.2 release being flagged by Defender

### ISSUE THREAD

**Issue by chrisjeter** [simulot/immich-go#353]
I downloaded the 0.18.2 release this morning from the repo. When trying to run an import Windows Defender is flagging the exe as a Trojan and Quarantining it as Win32/Bearfoos.A!ml. I've verified that all Defender signatures are up to date. 0.18.1 does not display the same issue. 
![Screenshot 2024-07-04 133513](https://github.com/simulot/immich-go/assets/36321541/b8ee08a6-145b-4001-84d3-6e0a414dc033)

**Comment by simulot** [comment]
The binary isn't signed, which is suspicious in Windows Defender eyes. I have tested the latest release with Windows Defender on a Win11 box. No detection.

I have checked the binary from the release with the virus total web site: 
https://www.virustotal.com/gui/file/dc7b3fc7873ffc23e3b8cd2da7e1b8e1b9345639fa5a4123ae9231d77f98ad2a/detection

1 positive over 74 tests. It's likely to be a false alarm.

The windows binary is complied on a linux box less susceptible to be infected. 
I'll check how to build the binaries in a secured environment and to sign the binaries.

**Comment by nontoxicmaxi** [comment]
Downloading
[immich-go_Windows_x86_64.zip]
(https://github.com/simulot/immich-go/releases/download/0.20.1/immich-go_Windows_x86_64.zip)

results in flag by antivirus. I suspect its a false positive, but nonetheless, would like confirmation that this software is safe to run?

**Comment by simulot** [comment]
@nontoxicmaxi
I'm compiling the windows version on a linux computer. 
I take all precautions to avoid any infection. But there is always a risk.

You can give a try to virus total to get the file tested with a bunch of antivirus
