### ISSUE TITLE
identify clearly any "context canceled" due to a network timeout

### ISSUE THREAD

**Issue by simulot** [simulot/immich-go#368]

**Comment by simulot** [comment]
Not reproduced:
```
GetAllAssets, POST, http://192.168.10.17:2283/api/search/metadata
Post "http://192.168.10.17:2283/api/search/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by simulot** [comment]
This is probably due to the size of the file (MP4). You can change the client time-out to give a chance to the server to complete the ingestion of the file. 
to give 30min, add   `-client-timeout=30m`  to the command

**Comment by Dunky13** [comment]
I'll try, had it on timeout for 10 min. But I'll try with increased timeout 👍
