### ISSUE TITLE
only one asset gets uploaded / unnecessary album gets created

### ISSUE THREAD

**Issue by traktuner** [simulot/immich-go#37]
Hello,
I try to upload some folders from my NAS to immich (jpg, jpeg, heic, dng).
The first folder I tried only contains about 200 .jpg files.
That would be my import command:

./immich-go -key xyz -server http://localhost:8050 -log-level INFO upload -album "xyz" /volume1/user/Pictures/Pictures/2000-01-01\ Test\ Test+Test/Assets/*.jpg

It does not matter if I write *.jpg at the end of if i completely removes it (I also tried to put the path between single ' and double " quotes).
immich-go creates two albums! The first which is called "." the second "xyz" -> why?
Also, only the first asset in the folder gets uploaded:

immich-go  0.3.5, commit 6b4c9454bd2c8a8a0cd65c0aee6ba6a686a97a61, built at 2023-10-14T20:54:19Z
Server status: OK
Connected, user: xyz
Get server's assets... 36748 received
Browsing folder(s)...Done.
1.jpg: This a new asset, upload it.
Uploading "1.jpg"...Done, total 1 uploaded
2 media scanned...
Create the album .
Create the album xyz
2 media scanned, 1 uploaded.
Done.

**Comment by simulot** [comment]
Thanks for using the project. 

The import of a plain old folder didn't received all the love it deserve.
I have fixed the code.
No more folder "."
All supported files added/

The last parameters on the immich-go upload command are meant to be paths, or path to zip.
Getting path/*.jpg doesn't work.
