### ISSUE TITLE
Shared albums not included from Google Photos takeout

### ISSUE THREAD

**Issue by muety** [simulot/immich-go#377]
I imported photos from Google Photos, but it looks like shared albums are not being created. With "shared" album I refer to albums that somebody else had created and I was invited to. I'd love to have these albums be created in Immich as well, but briefly investigating the takeout ZIP file made me wonder whether information about such albums is even included by any means?

**Comment by muety** [comment]
A tedious way to obtain this information could be through the Google Photos API.

First, [list albums](https://developers.google.com/photos/library/reference/rest/v1/albums/list) to get all album IDs (this included shared ones), then check which ones haven't been created in Immich yet, then [filter photos](https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search) by those albums' IDs and eventually create the album in Immich and assign the photos to them.

Unfortunately, Photos API doesn't support API key authentication, but only OAuth 2.0, which makes it even more tedious to integrate it in a command-line tool like Immich.

**Comment by simulot** [comment]
I'm afraid there is no way to get album you don't own.
As a workaround, you can download the album content from the Google photos web page and import them. But the quality is sub opeimal
