### ISSUE TITLE
not all GP duplicates are detected correctly, counters are wrong

### ISSUE THREAD

**Issue by simulot** [simulot/immich-go#380]
```sh
~$ for f in *.zip; do echo "$f: "; unzip -l $f | grep 130917ad28385b5a; done
immich-go_2024-07-15_09-48-52.zip:
takeout-20240712T112341Z-001.zip:
   167551  2024-07-12 13:38   Takeout/Google Foto/1 anno fa/130917ad28385b5a-photo.jpg
      808  2024-07-12 13:38   Takeout/Google Foto/1 anno fa/130917ad28385b5a-photo.jpg.json
takeout-20240712T112341Z-002.zip:
takeout-20240712T112341Z-003.zip:
      808  2024-07-12 13:52   Takeout/Google Foto/Photos from 2022/130917ad28385b5a-photo.jpg.json
takeout-20240712T112341Z-004.zip:
   167551  2024-07-12 13:45   Takeout/Google Foto/Photos from 2022/130917ad28385b5a-photo.jpg
takeout-20240712T112341Z-005.zip:
takeout-20240712T112341Z-006.zip:
takeout-20240712T112341Z-007.zip:
takeout-20240712T112341Z-008.zip:
takeout-20240712T112341Z-009.zip:
      808  2024-07-12 14:33   Takeout/Google Foto/Amsterdam 2022/130917ad28385b5a-photo.jpg.json
   167551  2024-07-12 14:33   Takeout/Google Foto/Amsterdam 2022/130917ad28385b5a-photo.jpg
      808  2024-07-12 14:35   Takeout/Google Foto/1 anno fa/130917ad28385b5a-photo.jpg.json
takeout-20240712T112341Z-010.zip:
   167551  2024-07-12 14:35   Takeout/Google Foto/1 anno fa/130917ad28385b5a-photo.jpg
```

**Comment by osa911** [comment]
I also had this issue when I tried to upload 40k+ photos to Immich via this tool. Unfortunately, everything was messed up, and It was difficult to find logs for you to open the issue
Btw, sometimes it sets the album logo from a different one. I think It was set because it found "duplicates" on this immense amount of photos (there are no duplicates)

**Comment by simulot** [comment]
@osa911
Depending on your OS:
- Linux $HOME/.cache/immich-go/immich-go_YYYY-MM-DD_HH-MI-SS.log
- Windows %LocalAppData%\immich-go\immich-go_YYYY-MM-DD_HH-MI-SS.log
- Apple $HOME/Library/Caches/immich-go/immich-go_YYYY-MM-DD_HH-MI-SS.log

The log path is displayed at the end of the process.

**Comment by osa911** [comment]
Yeah thanks
I mean it's difficult to share with you logs and real photos to find the issue. I'll try to do it by myself first and let you know 
But definitely, I can check the difference between the current and new version once you create😉
