### ISSUE TITLE
How do I know the script is continuing from where it was interrupted?

### ISSUE THREAD

**Issue by driftywinds** [simulot/immich-go#383]
I'm a bit of a noob and I wanted to understand how I would get to know that the script is continuing from where it was last interrupted. I tried restarting it once and it started back from 0, and that is why I was wondering. Thank you for your time!

**Comment by simulot** [comment]
You can interrupt the process at any time and relaunch it.
It will restart at the beginning but it wont upload again the files it has already uploaded

**Comment by driftywinds** [comment]
Thank you so much!!
