### ISSUE TITLE
Filename gets truncated when too long and replaced

### ISSUE THREAD

**Issue by bobokun** [simulot/immich-go#39]
I have an album where the filenames are really long `Backyard_ceremony_wedding_photography_location_xxxxxxxstudios-265.jpg` where the only difference is the end of the filename has a number associated to it. However, when running immich-go it seems to truncate the filename and therefore it does not upload all the photos but only one of them out of the x amount.

**Comment by simulot** [comment]
Thanks for using the project.

Could you give more context ?
How have you run the program?
- Have you imported a folder 
- Have you imported a google takeout archive
-

**Comment by bobokun** [comment]
I run using the command `./immich-go -server=https://photos.domain.com -key=xxx upload
-create-albums -google-photos -keep-partner -parner-album "partner's album" ./takeout*.zip`

This is run on linux. So far most files have been imported correctly and albums have been created, however I noticed 
1) the files with the long names like these ones do not get imported (because it thinks that it's the same filename when uploading. This is what I see in the logs when trying to log. It looks like the maximum characters it handles is 50 characters before the jpg extension.
```
Uploading "Takeout/Google Photos/Family _ friends/Backyard_ceremony_wedding_photography_cityxxx_m(1).jpg"...already exists on the server
Uploading "Takeout/Google Photos/Family _ friends/Backyard_ceremony_wedding_photography_cityxxx_m(1).jpg"...already exists on the server
Uploading "Takeout/Google Photos/Family _ friends/Backyard_ceremony_wedding_photography_cityxxx_m(1).jpg"...already exists on the server
...
Uploading "Takeout/Google Photos/Family _ friends/city_locationxxxxx_engagement_photography_magno(1).jpg"...already exists on the server
Uploading "Takeout/Google Photos/Family _ friends/city_locationxxxxx_engagement_photography_magno(1).jpg"...already exists on the server
Uploading "Takeout/Google Photos/Family _ friends/city_locationxxxxx_engagement_photography_magno(1).jpg"...already exists on the server
```

2) I also found another error in the upload process:
`can't find the image with title "IMG_20190518_145042.jpg", pattern: "IMG_20190518_145042*.*": file does not exist: "Takeout/Google Photos/Fami
ly _ friends/IMG_20190518_145042.jpg"`

3) I have photos that I have saved from partner sharing (I have turn on auto-save setting in google photos) but those aren't being uploaded too.

**Comment by simulot** [comment]
Google photos is a mess.

immich-go list files to be uploaded, search the json that match, and upload the file and give the title found in the json.

When the file name of the image/video is to long, the name is truncated with strange rules. 
Do we have an unplanned case?
- truncated name
- name with numbers in parenthesis

Could you give:
- the json name
- the title field in the json
- and what is is the difference between the video file name, the json name, and the title
thx

**Comment by bobokun** [comment]
Here is one example:
json name: `Backyard_ceremony_wedding_photography_xxxxxxx_(143).json`
title field in json: `"Backyard_ceremony_wedding_photography_xxxxxxx_magnoliastudios-254.jpg"`

json name has 419 items
jpg has 370 items

Unofrtunately the difference is not consistent, it is different for every file. In my one example the difference is 111 (254-143) however in other json files it's completely different and I can't find any pattern.

**Comment by simulot** [comment]
> json name has 419 items
> jpg has 370 items

do you mean the name has 419 characters?  
In the example you give, I'm not sure that the both are related.

> Unofrtunately the difference is not consistent, it is different for every file. In my one example the difference is 111 (254-143) > however in other json files it's completely different and I can't find any pattern.

The JSON is used to give the correct name and the correct date of take. The link between them is done by the name or a part of the name.  You see the difficulty. 

If you can share more data, I can search for the pattern.

**Comment by bobokun** [comment]
Do you have discord or some messaging app where I can send you the files? It's probably easier that way and I don't want to post these on GitHub where it's public

**Comment by simulot** [comment]
Sure, never done it before, apparently it's  simulot

**Comment by simulot** [comment]
So you takeout archive have several problems that can't be solved:

1. much less jpg than json files
2. no way to have an univoque link between the json and the jpg
3. the json capture date is wrong, and you jpg have no exif dates...

So I recommend to extract the album's folder and import the directory without the the option -google-photos

**Comment by simulot** [comment]
There is maybe a solution for your problem.
Stay tuned
