### ISSUE TITLE
Wrong creation date results in false album assignment

### ISSUE THREAD

**Issue by muety** [simulot/immich-go#392]
When importing from Google Photos, I ended up with albums containing photos that shouldn't actually be part of the album. I realized that this occurs when file name and creation date of the photos match, which is fair enough as an identifier. However, the date is wrong and doesn't match the actual creation date (as according to the metadata).

Here's an example of two photos. The first one got assigned to the album correctly, the second one is a false positive:

![Screenshot from 2024-07-19 15-28-04](https://github.com/user-attachments/assets/5b9aec08-1752-448c-8121-72326720e18c)
![Screenshot from 2024-07-19 15-28-12](https://github.com/user-attachments/assets/3bf6a3e4-a9ea-4972-9aac-a935f9e47d32)

And these's are the metadata files from the takeout:

[DSC_0032.jpg.json](https://github.com/user-attachments/files/16312605/DSC_0032.jpg.json)

[DSC_0032.jpg.json](https://github.com/user-attachments/files/16312604/DSC_0032.jpg.json)

Notice how both photos end up with the same date on Immich, even though they were taken on entirely different days. 

This is the command I used for the import:

```bash
immich-go -server http://localhost:2283 -key redacted upload -date=2024 -exclude-files=redacted1/ -google-photos takeout-*.zip
```

Did I miss something? Might also be a fault in my understanding of how to use the tool :man_shrugging:

**Comment by simulot** [comment]
You're right... 

Google Photos archives are full of oddities...
Look at https://github.com/simulot/immich-go/blob/main/docs/google-takeout.md
This combined by the poor file naming increase the difficulty.

I'm working on similar cases.
I can check you case. Send me logs to my discord @simulot 
Could you add the result of the following command: 
```sh
for f in *.zip; do echo "$f: "; unzip -l $f; done >list.lst
```

**Comment by muety** [comment]
Did you have time to look into this already? Let me know if I can support.

**Comment by simulot** [comment]
Yes, I did. I think I have fixed it.

**Comment by muety** [comment]
Is the fix pushed yet?

**Comment by simulot** [comment]
The fix is pushed
And thank you for your support 👍🏼
