### ISSUE TITLE
ValidateConnection, GET 404 Not Found

### ISSUE THREAD

**Issue by TheMarf** [simulot/immich-go#394]
Hello, have used this tool in the past with great success.  Something happened to my docker.img file so I'm starting immich from scratch.  I have seen other threads similar to this error but it sounded like it was resolved with v0.17.0 and later.  Tried the most recent 0.20.1 and received the error.  Do I need to roll back to an earlier version?

Immich version v1.109.2
Unraid version 6.12.11

![image](https://github.com/user-attachments/assets/f3d8d3ee-e7d3-4957-8f5b-454e1902902e)

**Comment by TheMarf** [comment]
Wait....I see its running 0.10.??? How the hell.  Let me blast the whole directory and try again.

**Comment by TheMarf** [comment]
Maybe I'm just too tired for this.  

![image](https://github.com/user-attachments/assets/645a2081-e983-48f4-ab73-42a3ddb78453)
![image](https://github.com/user-attachments/assets/18f29f42-23ab-4992-8aaa-22b0e199faca)

**Comment by simulot** [comment]
1st message: 
immich-go is too old for the version of immich server. 

2nd message: 
you have to decompress the tar.gz file: `tar -xf immich-go_Linux_x86_64.tar.gz` 


note than immich-go can run on you regular PC

**Comment by TheMarf** [comment]
Blowing away the directory took care of the first one since I didn't decompress the old immich-go was still there.

Decompressing it was the trick.  I don't remember doing that step last time.  Working well, thanks.
