### ISSUE TITLE
Problem with images with same name

### ISSUE THREAD

**Issue by StefanoBalocco** [simulot/immich-go#402]
Hello,
I downloaded a Google takeout (tgz) of my google photos library (around 25k+ photos).
I decompressed it and I've used immich-go to upload them in my immich library.

I've uploaded around 30 files named "camphoto_1804928587.jpg", in different albums (and with different content).

In an album called "Food" I've found 7 copies of "camphoto_1804928587.jpg" (instead of just the one with a pizza), and with wrong data.

**Comment by simulot** [comment]
I think I have solved this problem. 

You can send the result of following command to my discord @simulot 
```sh
for f in *.tgz; do echo "$f: "; tar -tzvf $f; done >list.lst
```
I'd be pleased to check how your use case is handled by the lastest code.

**Comment by simulot** [comment]
related to  #392
