### ISSUE TITLE
Files Without Extension

### ISSUE THREAD

**Issue by Jab2870** [simulot/immich-go#404]
First off, thanks for creating and maintaining Immich-Go

I have a whole bunch of files I would like to upload that don't have file extensions. In this case, they are the cache files used by signal-desktop.

They are stored as hashes as follows:

```
.
├── 0a
│  ├── 0a0a71f202b26b495df68bc16e90771eaa7b4cd92ddb14889b0cb454a7ef611b
│  ├── 0a017d40e75d77bcabb5388badea423d7f4f05dc0da85896ad7018fc69e55ba2
│  ├── 0a062c9fffa8ee153973eab5feb55f05678756ffbfe56e4689863f191f18f21b
│  ├── 0a07da8023d7d4e67e4c18e180e31b3f7e6f7cb659fc8bd87c5e1e2e6f3b34c6
│  ├── 0a1ab2039c1f2dbca2e4d102beabb108dc92d4fab5725cd122e657bf7c49c8c6
│  ├── 0a2df0acc9db3550551471ea67b1c6f296901847216da698d588b69d1f0b72f0
```

Of note is these are image files - they just don't have a .jpg or .png extention.

```
$ file 0a/0a017d40e75d77bcabb5388badea423d7f4f05dc0da85896ad7018fc69e55ba2
0a/0a017d40e75d77bcabb5388badea423d7f4f05dc0da85896ad7018fc69e55ba2: PNG image data, 150 x 150, 8-bit/color RGBA, non-interlaced
```

Trying to upload them, immich-go simply reports them as "unsupported files". Is there a way (other than renaming them all) to make immich-go look at the magic bytes of the file, rather than the extension?

**Comment by simulot** [comment]
alas no. Immich-go like immich are using the file extension to determine the file type.
