### ISSUE TITLE
motion photo files with MP~2 extension marked unsupported and skipped

### ISSUE THREAD

**Issue by tejesh83** [simulot/immich-go#405]
This is related to issue #106.  My takeout included ~32 Motion Photo files with a "MP\~2" extension that were flagged unsupported and skipped.

Here'a an example one:

```
INFO | unsupported file | file="Google Photos/Untitled(1)/PXL_20210102_221126856.MP~2" reason="unsupported file type" time="2024-07-24T06:23.42 EDT"

In that directory, there is a corresponding jpg and json file named:
PXL_20210102_221126856.MP~2.jpg
PXL_20210102_221126856.MP~2.jpg.json
``` 

In immich, I see that the .jpg has been uploaded but it's not shown as a motion photo.  It seems the "MP~2" is tripping this issue, as regular .MP files upload fine and display correctly as motion photos.  I'm not sure when google decides to use that extension, but my wife and I both use Pixel 7 phones, so it may have something to do with that device.  ~'I checked to see if there were any similary named files that necessitated the need to add "\~2" but that doesn't seem to be the case, at least in in the takeout folders.'~

FYI, in Google Photos it shown correctly as a motion picture.

**Comment by simulot** [comment]
Immich-go like immich use the file extension to determine the file type. .MP~ 2 is obviously not recognized.
However, I can check you case. Coud you share with me the list of takeout files?

something like 
```
unzip -l takeout*.zip | grep PXL_20210102_221126856 
```

**Comment by tejesh83** [comment]
By the way, immich-go is awesome!  Thank you for making this amazing utlity!!!  It made uploading my close to 750GB of takeout files a breeze.

I stand corrected, there are quite a few similarly named files.  I renamed one of the album folders below to pi_info since it had some family member names i'd prefer to keep private.  

      893  2024-01-21 16:33   Takeout/Google Photos/Family _ friends/PXL_20210102_221126856.MP.jpg.json
      896  2024-01-21 16:33   Takeout/Google Photos/Family _ friends/PXL_20210102_221126856.MP~2.jpg.json
      895  2024-01-21 16:52   Takeout/Google Photos/Untitled(1)/PXL_20210102_221126856.MP~2.jpg.json
      893  2024-01-21 16:52   Takeout/Google Photos/Untitled(1)/PXL_20210102_221126856.MP.jpg.json
      893  2024-01-21 17:46   Takeout/Google Photos/Photos from 2021/PXL_20210102_221126856.MP.jpg.json
      895  2024-01-21 17:46   Takeout/Google Photos/Photos from 2021/PXL_20210102_221126856.MP~2.jpg.json
  3242290  2024-01-21 16:58   Takeout/Google Photos/Untitled(1)/PXL_20210102_221126856.MP
  1214365  2024-01-21 16:58   Takeout/Google Photos/Untitled(1)/PXL_20210102_221126856.MP~2
  4028710  2024-01-21 16:59   Takeout/Google Photos/Untitled(1)/PXL_20210102_221126856.MP~2.jpg
  6486725  2024-01-21 16:59   Takeout/Google Photos/Untitled(1)/PXL_20210102_221126856.MP.jpg
  1214365  2024-01-21 15:40   Takeout/Google Photos/Family _ friends/PXL_20210102_221126856.MP~2
  3242290  2024-01-21 15:40   Takeout/Google Photos/Family _ friends/PXL_20210102_221126856.MP
  6486725  2024-01-21 15:41   Takeout/Google Photos/Family _ friends/PXL_20210102_221126856.MP.jpg
  4028710  2024-01-21 15:41   Takeout/Google Photos/Family _ friends/PXL_20210102_221126856.MP~2.jpg
  3242290  2024-01-21 17:53   Takeout/Google Photos/Photos from 2021/PXL_20210102_221126856.MP
  1214365  2024-01-21 17:53   Takeout/Google Photos/Photos from 2021/PXL_20210102_221126856.MP~2
  6486725  2024-01-21 17:53   Takeout/Google Photos/Photos from 2021/PXL_20210102_221126856.MP.jpg
  4028710  2024-01-21 17:53   Takeout/Google Photos/Photos from 2021/PXL_20210102_221126856.MP~2.jpg
  1214365  2024-01-21 16:14   Takeout/Google Photos/pi_info/PXL_20210102_221126856.MP~2
  3242290  2024-01-21 16:14   Takeout/Google Photos/pi_info/PXL_20210102_221126856.MP
      892  2024-01-21 16:14   Takeout/Google Photos/pi_info/PXL_20210102_221126856.MP.jpg.json
      895  2024-01-21 16:14   Takeout/Google Photos/pi_info/PXL_20210102_221126856.MP~2.jpg.json
  4028710  2024-01-21 16:14   Takeout/Google Photos/pi_info/PXL_20210102_221126856.MP~2.jpg
  6486725  2024-01-21 16:14   Takeout/Google Photos/pi_info/PXL_20210102_221126856.MP.jpg

**Comment by simulot** [comment]
This a new way for google to name files with the same name: using ~# instead of (#) for storing the files in the same folder.

I think the ~2 files are a modified version of the original file.
Add to my todo list

**Comment by tejesh83** [comment]
Tried out this weekend, worked great, thank you!
