### ISSUE TITLE
Can't import large assets

### ISSUE THREAD

**Issue by maya-doshi** [simulot/immich-go#41]
Command run: `./immich-go -server https://<url> -key <key> upload -create-albums -force-sidecar -google-photos GooglePhotos/takeout-20231019T010957Z-00*`

For the larger files in my collection I get this error:
`Error: AssetUpload, POST, https://<url>/api/asset/upload, 413 Request Entity Too Large`
immich-go is running on the same computer as Immich if that matters at all

I'm also getting the same error as #40 for deletion

**Comment by simulot** [comment]
the error 413 is given by the immich server.
What is the size of the file that cause the error?

**Comment by maya-doshi** [comment]
The files that gave errors were 5GB or greater.

**Comment by maya-doshi** [comment]
The files that gave errors were 5GB or greater. The error is on the server side, I get the same error when I try uploading from the website.

**Comment by simulot** [comment]
Good to know. thanks
