### ISSUE TITLE
[google photos] Lots of "No title" albums created with 1 file each

### ISSUE THREAD

**Issue by papinist** [simulot/immich-go#42]
Hi,
I tried to re-import my google takeout with the 0.37 release to see if something was missed before.
Besides uploading the same video with weird date of issue #23, I now have a lot (79) "no name albums (called "Senza titolo" in italian) with 1 image each. All are small images, I think they probably are from Hangouts sharing, however I don't know where it gets them from.

In folders, I have the same year 184894 with the same video, and a folder called "1" with a sub folder called 1-01-01 with many small images (but not the same from the "no title" albums). I tried to delethe both folders but still have all the "no title" albums and a "immich server error" when in immich main page.

**Comment by simulot** [comment]
Could past as screen shoot of the takeout directory tree? 
You can use my discord user simulot

**Comment by papinist** [comment]
Found out that I actually have 79 "Senza titolo" folders in my takeout!
So the strange thing still reamains all that 1-01-01 images, but it could be an issue of exiftool like for the video..

**Comment by simulot** [comment]
That's another evidence of takeout problem. I think those "untitled" albums come from share with whatsapp for example.
Images are normally placed somewhere else in the year's folder

I think I can add following command line options:

`-force-import-untitled TRUE/FALSE` with false as default.

When false, those folders would be ignored.
One difficulty here is that the name of the folder is translated into user's language.

Could you check that for real albums, the metadata files have a title field with a value?

**Comment by papinist** [comment]
> Could you check that for real albums, the metadata files have a title field with a value?

yes that's right:

```
{
  "title": "Auto americane",
  "description": "",
  "access": "protected",
  "date": {
    "timestamp": "1437837747",
    "formatted": "25 lug 2015, 15:22:27 UTC"
  },
  "location": "",
  "geoData": {
    "latitude": 0.0,
    "longitude": 0.0,
    "altitude": 0.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  }
}
```

and this is a "Senza titolo" one:

```
{
  "title": "",
  "description": "",
  "access": "",
  "date": {
    "timestamp": "0",
    "formatted": "1 gen 1970, 00:00:00 UTC"
  },
  "location": "",
  "geoData": {
    "latitude": 0.0,
    "longitude": 0.0,
    "altitude": 0.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  }
}
```

The option idea is good IMO.

**Comment by papinist** [comment]
Moreover, when Immich has some of this "wrong date" assets in his folders, I always get this "internal server error" message every time I go to main page. The last time, removing the video with 184... years also solved this issue, but this time I have removed both the video and the 1-01-01 folder and all assets in it, and the error persists.

I believe these images in "Senza titolo" folders could cause this issue, but I have to remove them manually...

**Comment by simulot** [comment]
So there is a way to discard untitled albums.

> Moreover, when Immich has some of this "wrong date" assets in his folders, I always get this "internal server error" message every time I go to main page. The last time, removing the video with 184... years also solved this issue, but this time I have removed both the video and the 1-01-01 folder and all assets in it, and the error persists.

I don't this is related to untitled albums. Its depends on exif information.
You can check it with following command:

```sh
exiftool -allDates 20161119_194320.mp4
Create Date                     : 174510:04:28 00:49:44
Modify Date                     : 2016:11:19 20:30:52
```
I expect that immich devs will implement a workaround. Otherwise, I'll check it before uploading the file, and force the use of sidecar.

**Comment by papinist** [comment]
Any way to batch-remove all these untitled albums from Immich?

**Comment by simulot** [comment]
> Any way to batch-remove all these untitled albums from Immich?

Not at the moment. If you dare it, you can try sql command.
