### ISSUE TITLE
Google takeout upload not consistent

### ISSUE THREAD

**Issue by GogoFC** [simulot/immich-go#422]
I uploaded the Google Photos takeout zip by running `immich-go -server=http://192.168.1.110:2283 -key=*** upload -google-photos takeout-20240803T203158Z-001.zip`

Then I re-run the command and it uploaded more files, so it's reasoning for choosing to upload or not isn't consistent and I can't trust it.

**Comment by simulot** [comment]
This should not happening.
Be sure you have processed all parts of the takeout at the same time. 
Compare the log files.
You can send them to me discord account.

**Comment by probablyVincentIp** [comment]
@simulot any update on this? I am having a similar issue

**Comment by simulot** [comment]
No, this should not happening, and is not reported either by other users. 

You can run the program twice and send me the logs.
the option  `-debug-counters` generates a CSV with the status all files.

**Comment by Saneckg** [comment]
I am having a similar issue

**Comment by simulot** [comment]
I need logs to check the problem.
