### ISSUE TITLE
Input and uploading numbers not adding up for google photos

### ISSUE THREAD

**Issue by Algid** [simulot/immich-go#423]
### The problem:
When using immich-go to upload my google photos takeout the numbers don't seem to add up correctly.

Looking at the results provided after an upload I see a total of 7212 images + videos, 34 are missing metadata files and one is discarded which ends with a total of 7177.

Looking at the uploading statistics and adding up all of the numbers I get a total of 6234 where I would expect a total of 7177 based on the section above.

Is there a reason for this discrepency I am not understanding or could this be due to an issue with immich-go itself?

I have provided some details below but am happy to provide any further details required.

### Details of configuration:

**Run command:**
```
./immich-go -server=XXXX -key=XXXX upload -dry-run=true -create-albums=false -create-albums -discard-archived -google-photos -debug-counters ./gt/takeout-*.zip
```

**My "gt" folder contains:**
```
takeout-20240704T140448Z-001.zip  takeout-20240704T140448Z-006.zip  takeout-20240704T140448Z-010.zip
takeout-20240704T140448Z-003.zip  takeout-20240704T140448Z-007.zip  takeout-20240704T140448Z-011.zip
takeout-20240704T140448Z-004.zip  takeout-20240704T140448Z-008.zip  takeout-20240704T140448Z-012.zip
takeout-20240704T140448Z-005.zip  takeout-20240704T140448Z-009.zip
```

Note I am missing the _-002_ file but this was a single video file which I uploaded separately.

**Run result:**
```
immich-go  0.21.0, commit 356bf1bdbc67d5a096ee11f8139c27d1ac5fdde9, built at 2024-07-30T14:45:20Z
. _ _  _ _ . _|_     _  _
|| | || | ||(_| | ─ (_|(_)
            v 0.21.0 _)


Input analysis:
---------------
scanned image file                      :    5361
scanned video file                      :    1851
scanned sidecar file                    :    6836
discarded file                          :       1
unsupported file                        :       5
file duplicated in the input            :       0
associated metadata file                :    7177
missing associated metadata file        :      34

Uploading:
----------
uploaded                                :       5
upload error                            :       0
file not selected                       :      10
server's asset upgraded with the input  :       0
server has same asset                   :    1877
server has a better asset               :    4342


Check the counters file:  /home/louis/.cache/immich-go/immich-go_2024-08-04_13-31-07.csv
Check the log file:  /home/louis/.cache/immich-go/immich-go_2024-08-04_13-31-07.log

34 JSON files are missing.
- Verify if all takeout parts have been included in the processing.
- Request another takeout,  either for one year at a time or in smaller increments.
```

**Comment by Algid** [comment]
Sorry I just noticed there was a new version and this seems to work perfectly - all of the numbers add up!

**Comment by simulot** [comment]
Good to know.
The initial miscount comes from some error while counting the motion pictures / live video

**Comment by Algid** [comment]
That makes sense, glad it provided some validation of the fix for that working correctly!

Thanks for all of your work on this project, made my life a lot easier moving my photos over.
