### ISSUE TITLE
Missing JSON file even though it exists

### ISSUE THREAD

**Issue by CoreoftheEarth** [simulot/immich-go#424]
While I am uploading my photos from a Takeout folder, immich-go claims to have 242 .json files that are missing. I looked at the logs that is put out after every upload operation and found which files that it said could not find their corresponding .json file for. I then searched for those files, and right next to them were the .json files that it said were "missing" when they were clearly not missing.

Why would immich-go claim those .json files are missing when they aren't? I analyzed a "missing" .json file verses a .json file that was _not_ marked as missing, and found no significant differences. 

Any ideas as to why this is happening and also for immich-go to be able to add the metadata from the "missing" .json file to its corresponding image?
![Screenshot 2024-08-04 163826](https://github.com/user-attachments/assets/6b717390-0a03-4455-8a96-e81be81865af)

**Comment by simulot** [comment]
The main reason for having missing JSON is to not process all parts of a takeout together.

You can share the log files, and if possible, the list of takeout content. 
https://github.com/simulot/immich-go/blob/main/docs/how-to-send-debug-data.md

**Comment by simulot** [comment]
Is this problem solved?

**Comment by CoreoftheEarth** [comment]
Yes, it turns out that after I tried it again with a new takeout package that, for whatever reason, everything went through just fine.
