### ISSUE TITLE
duplicate is not working?

### ISSUE THREAD

**Issue by yurividal** [simulot/immich-go#44]
I am running the duplicate command, with -yes at the end.
It finds and "removes" all the duplicates. But, then I run the same command again, and it finds the same duplicates again and "removes" again. It's like if it's not doing anything in reality.

**Comment by simulot** [comment]
Thanks for using the program.

I think it's linked to the new Trash functionality of immich 1.82. 
The files deleted files are placed in the trash be not actually deleted.

During the second run, the trashed images are still present and found as duplicates. 
You can see this: you'll have the best quality version accessible, and the low quality version in the trash.
Empty the trash, immigo won't find duplicates.

I think that I won't force the duplicate deletion. I'd rather ignore trashed files for the duplicate search.

**Comment by simulot** [comment]
Could you copy here the final report?
You can get a better understanding on what Immich-go does when enabling the -log-level=INFO

**Comment by recou** [comment]
no errors at all

```
./immich-go -log-level info -server http://x:y -key abc duplicate -yes
immich-go  0.10.0, commit 0d8a166dc9150b88e9ab37724dd52e7d682ce39c, built at 2024-01-28T17:15:17Z

Server status: OK
Connected, user: yx@xyx.xy
Get server's assets...68351 received
7154 duplicate(s) determined.
There are 2 copies of the asset 11052008(004).JPG, taken on 2008-05-11T17:30:45+02:00
  delete 11052008(004) 1280x960, 164.9 KB, /mnt/11052008(004).jpg
  keep   11052008(004) 1280x960, 164.9 KB, /mnt/11052008(004).jpg
  Asset removed
  
  ....

Done.
```

**Comment by simulot** [comment]
So the file isn't deleted. 
Is this one located in a library?
