### ISSUE TITLE
Server error - unexpected response

### ISSUE THREAD

**Issue by Soda47** [simulot/immich-go#452]
Hi everybody,

I want to import my pictures using immich-go but I get an the error : "unexpected response from server"

I'm running Ubuntu 24.04 und my command is like this :
./immich-go -server=https://192.168.178.20:7202 -key=************* upload -date 2019-07 {/media/myuser/mydrive/pictures}

When I enter the following adress in my browser https://192.168.178.20:7202/user-settings?isOpen=api-keys, I see a message "response pong". I guess then that the server works.

So I don't understand the problem ? What am I missing ?

Thanks for the support

**Comment by simulot** [comment]
The log should show it can't find the  the server at https://192.168.178.20:7202/api. 
Immich-go expect to find the API at the url of the WEB page + /api 

Apparently the API is at https://192.168.178.20:7202 
You can either:
- change the mapping of the URL on your proxy 
- use the option `-api=https://192.168.178.20:7202` in the place of the `-server=` option

**Comment by Soda47** [comment]
Merci Jean-Francois pour les explications,

I'll try that at home.

Have a nice day

**Comment by Soda47** [comment]
So I tested and found some things. 
The correct adress for me is https://192.168.178.20:7202/api/server-info/ping and in my browser, I see the response pong.

I wanted to use immich-go directly on my server but I still can't make if find the server.

However, I tested it on another machine and it works there.

**Comment by simulot** [comment]
When using the `-server=URL`, the API is found at URL+"/api'"
When using the '-api=URL`, the URL is used as provided.
