### ISSUE TITLE
Stacked images lose GPS metadata in Immich.

### ISSUE THREAD

**Issue by cooperaj** [simulot/immich-go#453]
I've got a strange issue that I've literally just noticed whilst cleaning up my Immich install. Any images that were stacked by immich-go have lost their mapping coordinates and do not show in the map view. I last ran immich-go sometime in early 2023.

If I use exiftool directly on the cover image on the raw storage it has coordinates. Immich also shows the reverse geoencoded address. If I manually stack some images now all images in the stack retain their mapping information.

Which leads me to believe that either a) Immich does not behave right when stacking using it's API or b) immich-go does (or did) not handle stacking correctly and removed the information.

For reference this is the latest Immich version but the *one* time I ran immich-go was using version 0.11 and it was to use the stack command so I didn't have to see the raw/burst files. I appreciate a lot has changed since 0.11 so this may no longer be relevant.

Any guidance on fixing this would be appreciated*. I know immich is in alpha and I should not use it as a primary image storage yadda yadda, but I really don't want to have to rebuild this library if I can avoid it.

*destacking and running metadata extraction does not seem to work, even though the exif data shows it's there.

EDIT.
In the hope of narrowing down the issue I've done some digging. It appears that the images that were stacked all have xmp sidecar files. The sidecars list the GPS as all zero's, deleting those files and running a refresh metadata task on the image brings the map information back i.e. the exif is correctly used. So I guess this issue can be narrowed to the fact that something (immich/immich-go) is creating bad/incorrect sidecars when stacking things?

**Comment by simulot** [comment]
I'm surprised by this result: all images are uploaded independently first, and then stacked.

Of course the immich and immich-go have changed a lot since March. Notably immich API has changed.
So it's impossible to test this in the same conditions.

**Comment by cooperaj** [comment]
Yeah, I figured as much. I used the stack command at the time so I'm not sure any actual uploads happened. I've just checked and basically all the sidecar files are empty of GPS data so I've just gone ahead and deleted them. I'm hoping a full extract job will work at this point but you never know.

**Comment by simulot** [comment]
The the stack command only call the API endpoint to stack photos.
So I don't think that the problem comes from immich-go.

**Comment by cooperaj** [comment]
I think you're right. Closing this. Thanks for the help :)
