### ISSUE TITLE
Windows x86_64 immediately closes

### ISSUE THREAD

**Issue by pastorjack** [simulot/immich-go#46]
Hello,
I'm on Windows 11 and I can't get it to work. I download the zip, extracted it, then tried to double click the .exe. It flashed the screen but vanished. Trying again with Windows task manager open revealed the immich-go task temporarily running after I double-clicked the .exe. I tried the latest release.
Thank you!
Jack

**Comment by simulot** [comment]
Thanks for using the tool. 
Immich-go is a command line tool. You must launch it from the terminal application with parameters.

With your description, I think you have run it from the explorer. The windows closes immediately because the program hasn't found the parameters he needs.
