### ISSUE TITLE
Google takeout zip imported with wrong dates - everything is imported to "today"

### ISSUE THREAD

**Issue by hakanu** [simulot/immich-go#460]
Thanks for the great tool, I have been using it for import my local photos. Then I decided to import google photos too, downloaded 20 parts of 50 gb zip files and used immich-go as suggested to do its magic. However, today I realized that the first 2 zips I imported had imported things with today's date even though EXIF info on the pics are correct in the takeout.

Also google photos albums are not imported, still immich shows zero albums which is less worrying than dates of the pics.

I triggered extract metadata job again but nothing happened. Is there any hope that I can somehow fix the dates? Or do I need to re-create the whole immich library (2.5TB) 

Thanks.

---

command I ran:

`./immich-go -server http://192.168.1.11:2283  -key KEY upload  -no-ui takeout-.zip`

**Comment by hakanu** [comment]
oh shoot thanks, my bad. would it fix the previously imported ones?

**Comment by simulot** [comment]
No way.. the date is a key to find existing images

**Comment by hakanu** [comment]
FWIW, for folks messed up like me, I deleted all the photos I uploaded yesterday on which I only did google photos import without -google-photos flag. Seems like I was able to clean up wrong dates and then immich-go again with-google-photos flag. Thanks!
