### ISSUE TITLE
ReadDir postgres: open postgres: permission denied

### ISSUE THREAD

**Issue by asimov44** [simulot/immich-go#465]
Hi. After several ok Upload. Now in other upload says: ReadDir postgres: open postgres: permission denied.
Any idea? 
Sorry my poor english.
Thank for all

**Comment by simulot** [comment]
No worry about the English... This concerns most of us...

Immich-go never talks directly to the immich database. The problem surely reside on the immich side. You should restart the immich server and watch log files.
