### ISSUE TITLE
Feature request: Use zip file name as album name

### ISSUE THREAD

**Issue by rbuchberger** [simulot/immich-go#466]
Hi! Again, thanks a ton for this software.

My Kid's preschool lets us download photos from time to time, and I like to archive them directly into Immich. They're provided as a flat zip file (no subdirectories).

If I use the `create-album-folder` option, they end up in an album called 'no-folder-name'. Would it be possible to use the name of the zip file instead?

```
INFO | added to an album | file=1000021615.jpg album=no-folder-name reason="option -create-album-folder" time="2024-08-30T10:13.01 CEST"
```

**Comment by simulot** [comment]
Have you tested with the option `-album="ALBUM NAME"` ?

**Comment by rbuchberger** [comment]
That's what I ended up doing, but I wrote a little script to set the album name from the name of each zip file. It was just a thought; taking the zip file basename as the album name might be better behavior than falling back to `no-folder-name`.

upload_photos() {
  for z in *.zip; do
    immich-go upload -album="${z%.zip}" "$z"
  done
}

**Comment by simulot** [comment]
It's on my todo list

**Comment by simulot** [comment]
It's included into the next major release.

**Comment by rbuchberger** [comment]
You’re amazing, thanks!

**Comment by simulot** [comment]
It is implemented the alpha release https://github.com/simulot/immich-go/releases/tag/v0.23.0-alpha2
