### ISSUE TITLE
unexpected response to the immich's ping api

### ISSUE THREAD

**Issue by hallofreunde12** [simulot/immich-go#472]
hi there,

from my unraid terminal after trying to upload google takeout like in the example usage
`./immich-go -server=192.168.178.99:9080 -key=*** upload -dry-run -create-albums -google-photos /mnt/user/path/takeout-*.zip` i get the error
> immich-go  0.22.0, commit 3cc0f052ae2e453ae2186d542a082a79bceaafb2, built at 2024-08-24T08:27:51Z
> Check the log file:  /root/.cache/immich-go/immich-go_2024-09-06_01-01-40.log
> unexpected response to the immich's ping API at this address: 192.168.178.99:9080/api/server-info/ping:

while the logfile `cat /root/.cache/immich-go/immich-go_2024-09-06_01-01-40.log` does not really help

>  INFO | Connection to the server 192.168.178.99:9080 | time="2024-09-06T01:01.40 CEST"
ERROR | unexpected response to the immich's ping API at this address: 192.168.178.99:9080/api/server-info/ping:
 | time="2024-09-06T01:01.40 CEST"

what i dont understand is that `curl http://192.168.178.99:9080/api/server-info/ping` seems to work
> {"res":"pong"}

what am i doing wrong?
i guess #452 had a compareable problem, alas no fulfilling resolution was found
greetings

**Comment by simulot** [comment]
Try following:

./immich-go -server=http://192.168.178.99:9080 -key=*** upload -dry-run -create-albums -google-photos /mnt/user/path/akeout-*.zip

**Comment by hallofreunde12** [comment]
aye that did the trick - 100% user error
thanks for the quick help and great piece of software

**Comment by TKaluza** [comment]
Ah god!
I looked at both commands multiple minutes until  ... the http:// 
Thank you!
