### ISSUE TITLE
Photos added to Immich without time value in datetime values, out of order in timeline.

### ISSUE THREAD

**Issue by FinlayWallenHalliwell** [simulot/immich-go#479]
I have used [icloud_photos_downloader](https://github.com/icloud-photos-downloader/icloud_photos_downloader) to bulk download my iCloud photo library. This has created a file structure of:
YYYY/MM/DD/img_xxxx.heic 

The files downloaded are original with full exif data including DateTime, DateTimeOriginal, Timezone etc.
All of these values are consistent and correct. e.g. 2022:05:21 12:20:48 for all datetimes and +12:00 for all TZs, Pacific/Auckland.

When uploaded to Immich via immich-go, the timeline is in order by date but completely out of order by time. The info panel on each image shows all datetimes as [correct date] 12:00 pm GMT+12.

The fields in the immich postgres assets table have been populated in this manner with no time values. E.g.
>"fileCreatedAt"
>"2022-05-21 00:00:00+00" 

Regenerating metadata in immich -> jobs does not seem to do anything. This [reddit thread](https://www.reddit.com/r/immich/comments/1ey7w00/reloading_metadata_from_the_original_pictures/) with the same issue might suggest that regenerating metadata isn't doing anything because the xmp sidecar files are already generated.

I believe this is a bug in that loss of timestamps in the immich ui, when uploading from a date based folder structure is not intended. The metadata determination behaviour is clearly [documented](https://github.com/simulot/immich-go?tab=readme-ov-file#metadata-determination) but the loss of usable timestamps is not.

This may more correctly be a feature request to force exif determination of metadata.

**Comment by FinlayWallenHalliwell** [comment]
Update: I was able to resolve this by deleting all the sidecar files with a python script. Immich automatically triggered an Extract Metadata job, and clean up the sidecar fields in the database immediately.

I'lll leave this open for consideration as a feature request for either
* Optionally forcing exif metadata regardless of the folder structure or filename.
* Optionally excluding sidecar files from the POST uploadAsset request, so that the Immich extract metadata job can run properly.

**Comment by simulot** [comment]
When there is a XMP files beside a photo, the file is always uploaded. Immich fills its database with a combination of data from the XMP and from the image. I don't have any Apple account. I can't reproduce your initial case without any sample.

> *  Optionally forcing exif metadata regardless of the folder structure or filename.

Currently, if a date can be found on the file path or name, immich-go assume this is the date of capture. That is a chip way to get 
this date without having to parse the file. 

In the next major version, I give the choice between no gess, file name, exif , and the use of exiftool.

> * Optionally excluding sidecar files from the POST uploadAsset request, so that the Immich extract metadata job can run properly.

Good idea. I'll add this option to the next major release.


Let me know if there is need for a better fit with ICloud Downloader

**Comment by FinlayWallenHalliwell** [comment]
Other than the datetime issue it works well with icloud photos downloader. There are no sidecars and json album spec files etc. I didnt think to try the iCloud Privacy download which I think is more similar to Google Takeout, perhaps that would be a better option for one time downloading as a seed to immich. 

Thanks!
