### ISSUE TITLE
Import from google takeout duplicates albums with special characters

### ISSUE THREAD

**Issue by papinist** [simulot/immich-go#48]
Hi, just did an import yesterday from google takeout (I already imported a takeout archive some weeks ago) and I noticed that albums with special characters (like &, " and so on) are considered new and not integrated with existing album. It seems that old version of Immich Go (I did the first takeout import on 29/9/23 and on 4/10/23 imported again the same archive) managed correctly special characters and version 0.37 did not.

Do you think I can fix it using "duplicate" function with 0.40?

![image](https://github.com/simulot/immich-go/assets/24779352/b258b2e9-2eb5-4b0d-a882-4602faa20330)

![image](https://github.com/simulot/immich-go/assets/24779352/8988f13a-8348-49f8-95b3-c6b826a4bcbe)

![image](https://github.com/simulot/immich-go/assets/24779352/57001911-a8ce-4b11-af2b-352078453fe3)

**Comment by simulot** [comment]
This come from contradictory wishes between having album named after the folder name and album named after the Album's title.

On #19, the takeout used to have several albums with the same title, but the user wants to keep them distinct in immich...

I'll add the option to give the choice of taking the folder name as album as fix for #42 
I think this will fix your problem too.

**Comment by papinist** [comment]
Thank you! Will this fix the already imported albums?

**Comment by simulot** [comment]
Alas no. There is no way to remember which albums have been created by imports or users.

I'm thinking about doing a cleaning tool for albums. But I'm busy with stack functionality.
