### ISSUE TITLE
"4 JSON files are missing"

### ISSUE THREAD

**Issue by HamonTeacher** [simulot/immich-go#493]
This error appears both when uploading two large archives and when uploading 6 smaller archives.

![image](https://github.com/user-attachments/assets/04d238e2-88b9-467e-bea7-8f1c9cda5b9e)
```
Some errors have occurred. Look at the log file for details
4 JSON files are missing. 
- Verify if all takeout parts have been included in the processing.
- Request another takeout,  either for one year at a time or in smaller increments.
```

**Comment by simulot** [comment]
Takeouts are not perfect, not documented.This leads to this kind of situation.

I can try to improve my code if you share details with me. Instructions are here: https://github.com/simulot/immich-go/blob/main/docs/how-to-send-debug-data.md
