### ISSUE TITLE
Not uploading ALL files?

### ISSUE THREAD

**Issue by Paulie420** [simulot/immich-go#497]
immich-go:

Input Analysis
Images     28382
Videos      12352

I've run immich-go three times and my Immich server shows:

701           Videos
25434     Photos

I'm going to export all video files into a different directory and see if there are indeed 12K - but has anyone else experienced this?? I just want to make sure Immich has ALL my photos/videos before I remove/delete my old ~/Pictures directory and backups... (Going to make a backup of the Immich server - but want to make sure.)

-----
So I moved all video files to their own directory, and re-ran immich-go. Al the files DO exist on the Immich server. What I THINK is... I took MANY iPhone 'motion' pictures. iOS pops those out as:

IMG_XXXX.MOV
IMG_XXXX.MOV.xmp
IMG_XXXX.JPG
IMG_XXXX.JPG.xmp

... I assume that Immich groups these together?? And hopefully the 'video' part of those are noticed through the .xmp information and linked w/ the entry??? Does this make sense to anyone - am I safe???

Thanks immich-go and responders!

**Comment by simulot** [comment]
You're probably safe.

Immich-go upload photos on to the server... You'll have a copy on the server and your source stays untouched.
Immicg-go filters thumbnails produced by some photo applications (synology, qnap....)

XMP files are metadata and are not accounted as video or photo. They are used by immich to get some context on the main file.

Immich-go does a duplicate check based on the file name and it size. It keeps only one sample of each photo
Immich also does a duplicate check based on the file content. It keeps only one sample of each photo

So, it's likely the explanation of the count difference.
You should read the log files produced by Immich-go to get better view on what did happened to each files.
