### ISSUE TITLE
Delete successfully migrated images from google

### ISSUE THREAD

**Issue by hartmark** [simulot/immich-go#507]
I would love to have an option to delete images that have been successfully migrated into immich.

One possible solution would be to use rclone mount to google-photo and remove images that have been imported.

Another question I have:
Whan happens if I run immich-go on a later takeout from google, will it detect which images that are already imported and just incrementally just add the new images?

**Comment by simulot** [comment]
Yes, it detect files already upload either by the phone or a previous immich-go run

**Comment by simulot** [comment]
> I doubt that rclone can delete remote photos.

It's not possible and google won't do it:
https://issuetracker.google.com/issues/109759781

**Comment by hartmark** [comment]
Oh, the google wall-in is even worse than I first thought :(

I guess I need to manually check that the images are in immich before deleting from google.

If I don't get any errors when running immich-go is it safe to assume that all images in the takeout have been added?

**Comment by hartmark** [comment]
It's quite the jungle to find stuff about the google photos api, but shouldn't this api work?
https://developers.google.com/photos/library/reference/rest

https://developers.google.com/photos/library/reference/rest/v1/albums/batchRemoveMediaItems

**Comment by simulot** [comment]
- Check the final report for any incoherence
- Don't worry too much about duplicates... this is a common issue of takeouts. Immich-go manage to upload only one sample of each image
- Check the number of "missing JSON"... If you have a more than an hand full, your takeout is probably faulty

**Comment by hartmark** [comment]
> * Check the final report for any incoherence
> 
>     * Don't worry too much about duplicates... this is a common issue of takeouts. Immich-go manage to upload only one sample of each image
> 
>     * Check the number of "missing JSON"... If you have a more than an hand full, your takeout is probably faulty

I'll do a fresh google photos takeout and watch out for any errors, after that I'll try delete my photos on google

**Comment by simulot** [comment]
> I read your linked thread, is it possible to move the images to a different album and then delete them in the web gui? https://issuetracker.google.com/issues/109759781#comment175

This possibility will be removed soon:
https://developers.googleblog.com/en/google-photos-picker-api-launch-and-library-api-updates/

**Comment by hartmark** [comment]
> > I read your linked thread, is it possible to move the images to a different album and then delete them in the web gui? https://issuetracker.google.com/issues/109759781#comment175
> 
> This possibility will be removed soon: https://developers.googleblog.com/en/google-photos-picker-api-launch-and-library-api-updates/

Aww, that sucks

**Comment by simulot** [comment]
No hope but cancelling the suscription
