### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by giannis371** [simulot/immich-go#514]
Every time i run the script im getting the error on 40%
Its around 15gb of files.

 INFO | server has same asset | file="Takeout/Google Fotos/Photos from 2021/Screenshot_20210122-225407_WhatsApp.jpg" reason="An asset with the same name:\"Screenshot_20210122-225407_WhatsApp.jpg\", date:\"2021-01-22 21:54:07\" and size:689.3 KB exists on the server. No need to upload." time="2024-10-21T01:15.22 CEST"
 INFO | server has same asset | file="Takeout/Google Fotos/Photos from 2021/20210503_193550.jpg" reason="An asset with the same name:\"20210503_193550.jpg\", date:\"2021-05-03 19:35:50\" and size:2.5 MB exists on the server. No need to upload." time="2024-10-21T01:15.22 CEST"
ERROR | upload error | file="Takeout/Google Fotos/Photos from 2022/20220423_122751.jpg" error="AssetUpload, POST, http://192.168.31.113:2283/api/assets, 500 Internal Server Error\nInternal Server Error\n" time="2024-10-21T01:15.22 CEST"
ERROR | upload error | file="Takeout/Google Fotos/Photos from 2022/20221030_120014.jpg" error="AssetUpload, POST, http://192.168.31.113:2283/api/assets, 500 Internal Server Error\nInternal Server Error\n" time="2024-10-21T01:15.22 CEST"
ERROR | upload error | file="Takeout/Google Fotos/Photos from 2022/20221016_163946.jpg" error="AssetUpload, POST, http://192.168.31.113:2283/api/assets\nPost \"http://192.168.31.113:2283/api/assets\": interrupted: Ctrl+C or Ctrl+Q pressed\n" time="2024-10-21T01:15.52 CEST"
 INFO | server has same asset | file="Takeout/Google Fotos/Photos from 2022/20221224_124808.jpg" reason="An asset with the same name:\"20221224_124808.jpg\", date:\"2022-12-24 11:48:08\" and size:1.9 MB exists on the server. No need to upload." time="2024-10-21T01:15.52 CEST"
 INFO | 
Input analysis:
---------------
scanned image file                      :    2951
scanned video file                      :      77
scanned sidecar file                    :    3078
discarded file                          :       1
unsupported file                        :       4
file duplicated in the input            :       0
associated metadata file                :    3027
missing associated metadata file        :       0

Uploading:
----------
uploaded                                :       0
upload error                            :       3
file not selected                       :      33
server's asset upgraded with the input  :       0
server has same asset                   :    1171
server has a better asset               :       0
 | time="2024-10-21T01:15.52 CEST"

**Comment by simulot** [comment]
This is an error thrown by the server. There root cause can be found on the server's logs. 
You can check the documentation https://main.preview.immich.app/docs/guides/docker-help#logs
