### ISSUE TITLE
Feature request: Remote machine learning fuction?

### ISSUE THREAD

**Issue by Fireflaker** [simulot/immich-go#515]
Hi!

I love this project and thank you for sharing it! It has saved me many hours of hassle.

It has the backbone for ready read/write to immich server, and I'm wondering if there is interest in integrating remote machine learning to improve accessibility on a PC. Right now there is a bit of a learning curve in setting up all the config files especially if the photo library is on a remote file server, and the GPU requires manual setup.
https://immich.app/docs/guides/remote-machine-learning/

If it's a far reach, or if it doesn't align with your vision, feel free to just close the issue. I am not familiar with go, but I'm looking to contribute as much as I can.

Much thanks!

**Comment by simulot** [comment]
I guess this issue doesn't concern immich-go , but the immich server.

**Comment by Fireflaker** [comment]
Thank you! I will look into that.
