### ISSUE TITLE
upload error 

### ISSUE THREAD

**Issue by ai30328348** [simulot/immich-go#517]
```
Input analysis:
---------------
scanned image file                      :   78608
scanned video file                      :     102
scanned sidecar file                    :       0
discarded file                          :       0
unsupported file                        :       0
file duplicated in the input            :       0
associated metadata file                :       0
missing associated metadata file        :       0

Uploading:
----------
uploaded                                :   76569
upload error                            :    2140
file not selected                       :       0
server's asset upgraded with the input  :       8
server has same asset                   :       0
server has a better asset               :       1

INFO | Connection to the server http://127.0.0.1:2283 | time="2024-10-24T06:59.12 CST"
 INFO | Server status: OK | time="2024-10-24T06:59.12 CST"
 INFO | Connected, user: xxx@xxx.com | time="2024-10-24T06:59.12 CST"
 INFO | Browsing folder(s)... | time="2024-10-24T06:59.12 CST"
...
ERROR | upload error | file=黑白/b39592cf1f1624d0e9b5d665e0dacf3103e6246c.jpeg error="AssetUpload, POST, http://127.0.0.1:2283/api/assets\nPost \"http://127.0.0.1:2283/api/assets\": EOF\n" time="2024-10-24T12:00.13 CST"
ERROR | upload error | file=动物/6bbd159e86508e61.jpg error="io: read/write on closed pipe\nAssetUpload, POST, http://127.0.0.1:2283/api/assets\nPost \"http://127.0.0.1:2283/api/assets\": write tcp 127.0.0.1:59114->127.0.0.1:2283: write: connection reset by peer\n" time="2024-10-23T07:31.07 CST"
...
```
Upload failed from a certain image, and left data in immich's database, but the file was not uploaded to immich, it is offline in immich, when re-uploaded, only this picture was detected as a duplicate and skipped on, the first image that failed to upload easily caused the picture to be lost hope to solve.

Also I would like to know why the upload fails.

**Comment by simulot** [comment]
I suspect a network error occurring at the first place.

Then, if immich refuse to upload it, this means that the server knows about those image. So it is probably uploaded.
Could you search for the image `b39592cf1f1624d0e9b5d665e0dacf3103e6246c.jpeg` on the server?

**Comment by ai30328348** [comment]
Searching for this file name in immich's webui and immich's library directory doesn't give you anything.
I stumbled upon an image thumbnail that didn't display properly, there was no information in immich's webui, so I suspected that there was something wrong with this image, and when I deleted this image in immich's webui, the image was not duplicated and was successfully uploaded

**Comment by ai30328348** [comment]
I guess it's because I set a 4G memory limit in docker and the memory is insufficient, so the system kills the immich process and causes the upload to fail.
In addition, when the storage template is album/file name, the file with the same name may be overwritten, resulting in face recognition failure, and one of the files will appear in different albums

**Comment by simulot** [comment]
Thank you for this report.
