### ISSUE TITLE
Duplicate command fails with 504 timeout.  

### ISSUE THREAD

**Issue by happytaz** [simulot/immich-go#52]
Duplicate command fails with 504 timeout on a library of 130K.  It works fine on a smaller library of 3K.

Immich server is on a RPi 4 with external USB storage.

**Comment by happytaz** [comment]
Yes, the error seems to occur while it's pulling image data.  This is the error message:

←[32mServer status: OK←[39m
←[32mGet server's assets...←[31mGetAllAssets, GET, http://192.168.1.123:2283/api/asset, 504 Gateway Timeout
←[39m

**Comment by simulot** [comment]
Maybe th PI4 is out of breath.

Both start with a getAssets. At the moment this returns a big JSON file with data of all images.
There is no way to avoid this.

**Comment by happytaz** [comment]
Very little CPU and RAM being used on the Pi4.  

The timeout appears connected to the immich proxy:

https://github.com/immich-app/immich/issues/3208

Is is possible to get immich-go working on the server directly(port 3001) without going through immich proxy?

**Comment by simulot** [comment]
Not at the moment. 

But you can test:
edit the docker_compose.yml file and expose the server port:
```yml
    ports:
      - 3001:3001
```

You can curl the api:
```
curl http://localhost:3001/asset?apiKey=theprivatekey
```

**Comment by happytaz** [comment]
I did as you instructed with adding port 3001 to my docker compose file and the curl command returned a bunch of image data.

I tried to run the immich-go duplicate command with port 3001 and got the following error:

←[31mPingServer, GET, http://192.168.1.100:3001/api/server-info/ping, 404 Not Found
Not Found
←[39m

**Comment by simulot** [comment]
Well, I'll add a  way to to bypass the proxy.
Stay tuned.


I have opened an discussion at the immich project for changing the way to retrieve this mass of data.
https://github.com/immich-app/immich/discussions/4778

**Comment by simulot** [comment]
The fix is ready. 
But I doubt it will work when your library will grow.

I'm about the release it

**Comment by happytaz** [comment]
Just tried your new release.  Same error:

←[32mServer status: OK←[39m
←[32mGet server's assets...←[31mGetAllAssets, GET, http://192.168.1.123:2283/api/asset, 504 Gateway Timeout
←[39m

**Comment by simulot** [comment]
You have to substitute the -server by the -api with the container address and port. Drop the /API from the URL

**Comment by happytaz** [comment]
This is my command:

immich-go -server=http://192.168.1.123:2283 -key=********************* duplicate -yes

I don't have /API in the url.  What am I missing?

**Comment by simulot** [comment]
Change the -server by -api

**Comment by happytaz** [comment]
Thank you so much! Duplicates are currently getting removed.

**Comment by simulot** [comment]
Was it successful?

Could you check #60 ?

**Comment by happytaz** [comment]
Yes, it was successful.  I had 27K duplicates.  It would have taken me days/weeks to manually remove.  Thanks again!
