### ISSUE TITLE
Failed to get local machine timezone: "/etc/localtime" is not a symlink - cannot infer name

### ISSUE THREAD

**Issue by seryrzu** [simulot/immich-go#525]
Running either the [latest build for Linux x86_64](https://github.com/simulot/immich-go/releases/download/0.22.1/immich-go_Linux_x86_64.tar.gz) or building `immich-go` from source, results in the following issue.
```
$ ./immich-go --help
panic: failed to get local machine timezone: "/etc/localtime" is not a symlink - cannot infer name

goroutine 1 [running]:
github.com/simulot/immich-go/immich/metadata.init.0()
        /var/services/homes/seryrzu/soft/immich-go/immich/metadata/timezone.go:15 +0x5c
```

I do this on a Synology NAS, that is technically a Linux
```
uname --all
Linux <> 4.4.302+ <> Fri Jan 12 17:01:14 CST 2024 x86_64 GNU/Linux <>
```
and Linux is [supposed to (?)](https://serverfault.com/a/642285) have a symlink at `/etc/localtime`, but in my case it is a binary.

A temporary fix that I found is to set env variable first
```
$ export TZ="America/Los_Angeles"
./immich-go --help
```

It would be cool if there is an automated solution for this or at least a clarification in the manual.
Thanks!

**Comment by simulot** [comment]
Another workaround is to use the `time-zone=time_zone_name` option

I don't know how to make it working in all cases. I was glad enough to get it working for linux (ubuntu at least), freeBSD and MacOS 😅 
I think to remove this dependence in the future.
