### ISSUE TITLE
Add an option to prefer getting metadata from file's exif

### ISSUE THREAD

**Issue by chenyanzhe** [simulot/immich-go#526]
My photos are organized in a directory structured like `YYYY/MM/DD/MY_IMAGE_NAME.JPG`. When I use immich-go to upload them, the photo's capture date is resolved to `YYYY-MM-DD 00:00:00`. This causes the photos within a single day are randomly ordered.

I understand the behavior right now, which is aligned with the [documentation](https://github.com/simulot/immich-go?tab=readme-ov-file#metadata-determination). But since my photos have `exif` metadata so I would like to use them in Immich server.

Is there a way to ask immich-go to determine the capture date from `exif` instead of the directory path? Or, alternatively, ask immich-go to skip retrieving metadata during upload (a.k.a, don't generate .xml file for each photo), instead let Immich server to figure this out by itself?

**Comment by simulot** [comment]
Yes, but with the next version. Exif is the default, but you can control how it's used.

https://github.com/simulot/immich-go/releases/tag/0.23.0-alpha3

**Comment by vandershraaf** [comment]
Just want to add that I had same issue when bulk import through immich-go. Turns out it was because I was using the latest release 0.22.1. Once I updated to latest beta release 0.23.0-alpha5, the dates are set correctly. Hope we can get the new non-beta release soon. Thanks!

**Comment by simulot** [comment]
Thank you for the report. 
I was calling Immich's API with a local date. Immich doesn't like too much. 

On the other hand, immich handles capture dates correctly, most of the time. 

I propose to implements the following:

if the photo's metadata has a capture date, pass the photo to immich, with no date.
otherwise, a date is available either in a JSON/XMP files, or in the file name, force the date.

**Comment by itskagee** [comment]
I used the stable release and have the same problem.

Considering I have already uploaded like 30k files already, is there a way through which I can change the dates on the server correctly now?

**Comment by simulot** [comment]
the version v0.23.rc2 completely changes the way that immich-go pass the metadata to immich.
Now, Immich-go changes the date of capture only when the date is missing from the photo's metadata, the `--date-from-name` is used and the file path is named after a date.
