### ISSUE TITLE
unexpected response to the immich's ping API at this address

### ISSUE THREAD

**Issue by J3a90r** [simulot/immich-go#546]
Hello,

I'm sorry, but i'm try to use immich-go from several days and i don't undersatnd my errors.

Im' using immich-go 0.22.1 ( for windos) and Immich server V1.121.0 in Openmediavault's Docker on Raspberry.

I use this command line : immich-go -server=http://192.168.1.17:2283 -key=**key** upload from-google-photos takeout-*.zip

And i receve and errors message  : unexpected response to the immich's ping API at this address: erver=http://192.168.1.17:2283/api/server/ping:

When i try this adresses i receve : 
{"res":"pong"}

Could you help me please i have 6 takeout zip ti upload.

Thx for you help

Seen u

**Comment by simulot** [comment]
Could you run immich-go with the `-api-trace` option?
The log file shows exactly what immich-go does withe the immich server.

I suspect some network error.

**Comment by simulot** [comment]
with the RC version the flag is `--api-trace`

**Comment by simulot** [comment]
The trace file located beside the log file

**Comment by J3a90r** [comment]
I Juste try as you mention with some double -- it's working fine thx a lot
