### ISSUE TITLE
Immich Merging Together JPGs and MOVs incorrectly

### ISSUE THREAD

**Issue by shaankhosla** [simulot/immich-go#554]
I have a number of incorrectly created live photos. JPGs and MOVs were merged together because they have the same filename, but the creation date of the photo should be used to determine if they are actually supposed to be merged together.

**Comment by shaankhosla** [comment]
Created an [issue](https://github.com/immich-app/immich/issues/14459) on Immich as well that was closed.

**Comment by simulot** [comment]
This is fixed with the RC version.
Have you tested it?

**Comment by shaankhosla** [comment]
Thanks, I'll give it a try

**Comment by shaankhosla** [comment]
This worked! One problem though--those photos are now stacked together, I think because the tool thinks they're in a burst. Is there a way to disable stacking when uploading?

**Comment by simulot** [comment]
Could you share the log file? 
You can share it privately on my discord account @simulot
