### ISSUE TITLE
add filter on directories during the import

### ISSUE THREAD

**Issue by simulot** [simulot/immich-go#58]
Libraries that used to be manged by another software have additional thumbnails that shouldn't be uploaded into immich. 
Exemple;
- @eaDir
-

**Comment by simulot** [comment]
This is now implemented

**Comment by rui-nar** [comment]
hey, I'm not seeing any option to exclude directories .
How do you go about specifying that directories "@eaDir" should be excluded ? (I'm on version 0.15.0)
thanks
