### ISSUE TITLE
Golang error: "unknown time zone America/Los_Angeles"

### ISSUE THREAD

**Issue by joshua-holmes** [simulot/immich-go#580]
I am not a Golang programmer, so maybe this is not an issue that can immich-go can fix, but when I install the `immich-go` binary and run it, I get this:
```
$ immich-go
panic: unknown time zone America/Los_Angeles

goroutine 1 [running]:
github.com/simulot/immich-go/immich/metadata.init.0()
	github.com/simulot/immich-go/immich/metadata/timezone.go:15 +0x5c
```

The way I fixed it is by downloading this TZ file:
```shell
wget https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip
```
and then setting the `ZONEINFO` env var to the file I just downloaded before running `immich-go`:
```shell
env ZONEINFO=zoneinfo.zip immich-go
```

Is there a way to include the data that comes from `zoneinfo.zip` into the build process and set the env var there? This seems like an odd requirement to run a binary.

I'm on vanilla Arch Linux, kernel 6.12.4-arch1-1

Using immich-go version 0.22.1, installed from my package manager

**Comment by simulot** [comment]
The zoneinfo file is embedded with the regular releases  available on GitHub.
I don't know how the package for arch linux is built. You may reach the package maintainer.

**Comment by joshua-holmes** [comment]
Oh ok, great to know. Thanks!
