### ISSUE TITLE
API users/me returns 401

### ISSUE THREAD

**Issue by jocon-grmtx** [simulot/immich-go#589]
Hello,
I was wondering if I could get some help.  After several hours of trying to get immich-go working today, I continue getting a 401 no authorization.  I can call the api via browser with good results.  

The command I am using:
`.\immich-go.exe -server=http://192.168.68.99:8212 -key=<my gen api key from portainer>= -skip-verify-ssl upload -google-photos -dry-run=TRUE -date=2024 C:\Users\jac\Downloads\takeout-20241228T211124Z-*.zip
`

![igo401](https://github.com/user-attachments/assets/b11ea2a6-bdda-468d-aa92-02e03b42cb40)

I am assuming the API key is from my portainer account. I could not find a 'immich' api generator, and even tried to call the createApiKey api, but there is no response from the request.

Does anyone have any idea about this?  I am not a developer :] but trying my best.  Thank you - John

**Comment by simulot** [comment]
You need an API from Imich itself.
![image](https://github.com/user-attachments/assets/cd82221e-faa9-463b-88fc-3dba91934fe4)
Then:
![image](https://github.com/user-attachments/assets/df733f74-ad0e-41f5-9f48-46b592e48f9e)
