### ISSUE TITLE
External Library Path validation error

### ISSUE THREAD

**Issue by jocon-grmtx** [simulot/immich-go#592]
Hello,
Today I was trying to define an external library to point to a path in my Synology NAS where I have most of my photos.
This would appear to be easy, but I get a 'Path Validation Warning', then a 'Invalid import path'.  See attached.
I have tried different variations on the path specification but this should be the correct path /volume1/photo

I installed immich following [this guide](https://mariushosting.com/how-to-install-immich-on-your-synology-nas/). 

![immichExternalLibError1](https://github.com/user-attachments/assets/683a4169-fd4f-4b95-9fbb-90271a7a3885)

Any help appreciated - Thanks again, John

**Comment by simulot** [comment]
You should post this issue in the immich server repository. 
This one concerns only immich-go

**Comment by jocon-grmtx** [comment]
Thank You Jean Fancois.  My bad.  Happy New Year - John
