### ISSUE TITLE
 The term 'immich-go' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by seanbydesign** [simulot/immich-go#594]
hello, I have installed Immich-go into windows directory, including the immich-go exe. Run the location in powershell, and used the following command:

immich-go -server=http://192.168.50.77:8080 -key=XXXXXXXXXXXXXXXXXXXXX upload -create-albums -google-photos takeout-*.zip

I get the response: immich-go : The term 'immich-go' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

I have 7 Google Takeout folders at 50GB each ready to go into Immich from my home computer, but I can't get the command to run no matter what I do.

Immich is self hosted on the local network via unRaid, I can do this from unraid, however I don't even know where to start or how to install it there. I guess my main issue, even through immich-go has a programfiles location /go and bin and is all there, it doesn't work. 

Not sure how to by-pass this error. Many thanks.

**Comment by simulot** [comment]
Try to prepend the command by a `.\`
```
.\immich-go -server=http://192.168.50.77:8080/ -key=XXXXXXXXXXXXXXXXXXXXX upload -create-albums -google-photos takeout-*.zip
```

**Comment by seanbydesign** [comment]
Thank you so much this worked. Appologies for the simple issue! Thank you
