### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by gofaster** [simulot/immich-go#64]
Attempting to test immich-go but getting segfault.  Am I invoking it with the wrong parameters?
`Ubuntu 22.04.6 LTS ` `5.15.0-86-generic #96~20.04.1-Ubuntu SMP Thu Sep 21 13:23:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
```
$ immich-go -server http://xxx.xxx.xxx.xxx:2283 -key xxxx upload -dry-run '/path/*.JPG'
immich-go  0.8.1, commit e25849759e0ddcffaa75e071c12abd90c378d1af, built at 2023-11-09T20:19:31Z
Server status: OK
Connected, user: user@example.org
Ask for server's assets...
4974 asset(s) received
Browsing folder(s)...Done.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7a8a9f]

goroutine 1 [running]:
immich-go/cmdupload.(*UpCmd).Run(0xc00022e140, {0x984490, 0xc00007a0f0})
        /home/jfcassan/Dev/immich-go/cmdupload/upload.go:238 +0x2df
immich-go/cmdupload.UploadCommand({0x984490, 0xc00007a0f0}, {0x986930?, 0xc00007a140?}, 0xc000153b78?, {0xc000022310?, 0x1?, 0x4?})
        /home/jfcassan/Dev/immich-go/cmdupload/upload.go:201 +0x4c
main.Run({0x984490, 0xc00007a0f0}, 0x1?)
        /home/jfcassan/Dev/immich-go/main.go:144 +0xefa
main.main()
        /home/jfcassan/Dev/immich-go/main.go:47 +0x28b
```

**Comment by simulot** [comment]
Probably not. It's not supposed to crash.

Could you share more context? 
What was the command line?

**Comment by simulot** [comment]
Forget the question. I have reproduced you case on my system. 
Stay tuned.

**Comment by gofaster** [comment]
Sorry I misunderstood the last parameter. Thank you for looking into it!
To be precise,  the path I used in this specific case is `'/path/with spaces/'*.JPG` where only the part with spaces ia quoted but not the glob.

**Comment by simulot** [comment]
I think I'll add a parameter to select specific extensions.

**Comment by simulot** [comment]
The segfault is fixed. 
I'll add later the option to select only images with a given extension.
