### ISSUE TITLE
Live photos files are stacked and not recognized as live photos

### ISSUE THREAD

**Issue by jdohnstad** [simulot/immich-go#67]
I believe that this is an immich-go issue and not Immich itself - I apologize if that is incorrect.

I imported a Google Takeout using immich-go (0.8.2) via:

`immich-go.exe -server <my hostname> -key <my key> upload -create-albums -google-photos '.\Google Takeout\takeout-*.zip'`

and noticed that a fairly significant number of thumbnails were broken. This persisted after rerunning the Immich thumbnail generation job. I pulled up the Immich microservice logs, and found a bunch of errors similar to:

```
[Nest] 7  - 11/14/2023, 2:21:15 AM   ERROR [JobService] Error: Input file has corrupt header: magickload: Magick: ImproperImageHeader upload/library/admin/2023/2023-10-31/IMG_5580+1.HEIC' @ error/tga.c/ReadTGAImage/239 (null)

[Nest] 7  - 11/14/2023, 2:21:15 AM   ERROR [JobService] Object:

{

  "id": "27d07cd1-78ab-463f-bcfd-1bebd40e2c26"

}
```

I traced this file back to the Google Takeout archive which contained the following files:

> IMG_5580.HEIC
> IMG_5580.HEIC.json
> IMG_5580.MP4

and within my Immich library after the import I can see:

> IMG_5580.HEIC
> IMG_5580+1.HEIC

So it would seem that the .MP4 file got imported incorrectly as an HEIC file, and now thumbnail generation fails because its an unexpected file type. I did a comparison of the actual byte-content of the files, and the actual content is correct.

**Comment by twau** [comment]
This sounds like the issue I’m also experiencing on my new test Immich install, asked if anyone else had encountered the issue here #66, seems like there is a problem.

**Comment by simulot** [comment]
Thanks for your investigation.

It might be the case. I don't have an iPhone, so I haven't handled this case.

Could you share the Json file content(I need this one), and if possible a sample of heic file or a random sample of this kind of file?

**Comment by jdohnstad** [comment]
While tracking down a file I was comfortable sharing, I found a similar situation with a .JPG, and an .MOV that was uploaded as an mp4. I agree with @twau - it seems like generally its "Live Photos" where there is both an image and a short video clip alongside it. In my previous example with the .HEIC, I only see one sidecar json file. In this sample I've attached there is a json sidecar for both the jpeg and the .MOV

[sample.zip](https://github.com/simulot/immich-go/files/13371634/sample.zip)

**Comment by jdohnstad** [comment]
Also the json for the original reported HEIC:

[IMG_5580.HEIC.json](https://github.com/simulot/immich-go/files/13371646/IMG_5580.HEIC.json)

**Comment by simulot** [comment]
Thank you all for your files.

**Comment by twau** [comment]
Uploaded my google takeout to a new immich install again to check if this fix works, and most of my LivePhotos is now displayed correct. But there is still issues with LivePhotos, will try to find more examples to upload later tonight.

For example, a few of my LivePhotos were found in the trash after the upload, the .qt movie from the LivePhotos was saved with the broken thumbnail, and the .heic file was placed in the trash
