### ISSUE TITLE
Panic: runtime error: slice bounds out of range [-29:]

### ISSUE THREAD

**Issue by simulot** [simulot/immich-go#69]
Seen on discord jODIN || ⚔

```
pano_share-02.jpeg: An asset with the same name:"pano_share-02", date:"2019-12-31 12:23:56" and size:3.5 MB exists on the server. No need to upload.
37230 media scanned...
panic: runtime error: slice bounds out of range [-29:]

goroutine 24 [running]:
immich-go/immich/metadata.searchPattern({0x980b80, 0xc0001a9188}, {0xc001fe9794, 0x4, 0x4}, 0x3c)
    /home/jfcassan/Dev/immich-go/immich/metadata/search.go:42 +0x285
immich-go/immich/metadata.readMP4DateTaken({0x980b80?, 0xc0001a9188?})
    /home/jfcassan/Dev/immich-go/immich/metadata/direct.go:79 +0x45
immich-go/immich/metadata.GetFromReader({0x980b80, 0xc0001a9188}, {0xc001e58bcd, 0x4})
    /home/jfcassan/Dev/immich-go/immich/metadata/direct.go:44 +0x106
immich-go/assets/files.(*LocalAssetBrowser).ReadMetadataFromFile(0xc001e58bb8?, 0xc001f116c0)
    /home/jfcassan/Dev/immich-go/assets/files/localassets.go:121 +0xa5
immich-go/assets/files.(*LocalAssetBrowser).Browse.func1.1({0xc001e58b90, 0x41}, {0x9845e0, 0xc001a31540}, {0x0, 0x0})
...
```

**Comment by BenSanborn** [comment]
If this is of any help to you, I have also seen this issue 3-4 times in last day.

Uploading "Google Photos/Photos from 2016/IMG_20161222_174908-edited.jpg"...already exists on the server
Creating stacks
  Stacking MVIMG_20181018_173636.MP4, MVIMG_20181018_173636.jpg...
panic: runtime error: slice bounds out of range [32716:32707]

goroutine 10 [running]:
immich-go/immich/metadata.searchPattern({0x63da40, 0xc0001c0d20}, {0xc00b7a3854, 0x4, 0x4}, 0x3c)
        /home/jfcassan/Dev/immich-go/immich/metadata/search.go:42 +0x285
immich-go/immich/metadata.readMP4DateTaken({0x63da40?, 0xc0001c0d20?})
        /home/jfcassan/Dev/immich-go/immich/metadata/direct.go:79 +0x45
immich-go/immich/metadata.GetFromReader({0x63da40, 0xc0001c0d20}, {0xc0070d4cb2, 0x4})
        /home/jfcassan/Dev/immich-go/immich/metadata/direct.go:44 +0x106
immich-go/assets/files.(*LocalAssetBrowser).ReadMetadataFromFile(0xc0070d4c9f?, 0xc006433b20)
        /home/jfcassan/Dev/immich-go/assets/files/localassets.go:121 +0xa5
immich-go/assets/files.(*LocalAssetBrowser).Browse.func1.1({0xc0070d4c80, 0x36}, {0x641440, 0xc00a3d9f80}, {0x0, 0x0})
        /home/jfcassan/Dev/immich-go/assets/files/localassets.go:73 +0x346
io/fs.walkDir({0x63dc20, 0xc00002a510}, {0xc0070d4c80, 0x36}, {0x641440, 0xc00a3d9f80}, 0xc00b7a3f80)
        /usr/local/go/src/io/fs/walk.go:73 +0x6c
io/fs.walkDir({0x63dc20, 0xc00002a510}, {0xc00930a200, 0x1e}, {0x641440, 0xc0000d7ce0}, 0xc00b7a3f80)
        /usr/local/go/src/io/fs/walk.go:95 +0x2c5
io/fs.walkDir({0x63dc20, 0xc00002a510}, {0xc004a51fe0, 0xd}, {0x641440, 0xc0000d6150}, 0xc00b7a3f80)
        /usr/local/go/src/io/fs/walk.go:95 +0x2c5
io/fs.walkDir({0x63dc20, 0xc00002a510}, {0x6399e0, 0x1}, {0x6414e8, 0xc0001f0e70}, 0xc00b7a3f80)
        /usr/local/go/src/io/fs/walk.go:95 +0x2c5
io/fs.WalkDir({0x63dc20, 0xc00002a510}, {0x6399e0, 0x1}, 0xc00049bf80)
        /usr/local/go/src/io/fs/walk.go:122 +0xd2
immich-go/assets/files.(*LocalAssetBrowser).Browse.func1({0x6412f0, 0xc00011a0a0})
        /home/jfcassan/Dev/immich-go/assets/files/localassets.go:37 +0xdf
created by immich-go/assets/files.(*LocalAssetBrowser).Browse in goroutine 1
        /home/jfcassan/Dev/immich-go/assets/files/localassets.go:35 +0xed
PS C:\Google Takeout> ./immich-go -server=http://192.168.1.174:765/ -key=DU1sChMFZmVJNb530pbVenA2s7lyVpIUYSdEkiwbE upload -create-albums Takeout
immich-go  0.8.2, commit 0792ade89f7f556c82225138e36fb9aa6f028576, built at 2023-11-11T20:07:29Z


215096 media scanned, 0 uploaded.
Done.
panic: runtime error: slice bounds out of range [32716:32707]

goroutine 9 [running]:
immich-go/immich/metadata.searchPattern({0x63da40, 0xc00b8e7d28}, {0xc00bb11854, 0x4, 0x4}, 0x3c)
        /home/jfcassan/Dev/immich-go/immich/metadata/search.go:42 +0x285
immich-go/immich/metadata.readMP4DateTaken({0x63da40?, 0xc00b8e7d28?})
        /home/jfcassan/Dev/immich-go/immich/metadata/direct.go:79 +0x45
immich-go/immich/metadata.GetFromReader({0x63da40, 0xc00b8e7d28}, {0xc005f5f8b2, 0x4})
        /home/jfcassan/Dev/immich-go/immich/metadata/direct.go:44 +0x106
immich-go/assets/files.(*LocalAssetBrowser).ReadMetadataFromFile(0xc005f5f89f?, 0xc005f2d960)
        /home/jfcassan/Dev/immich-go/assets/files/localassets.go:121 +0xa5
immich-go/assets/files.(*LocalAssetBrowser).Browse.func1.1({0xc005f5f880, 0x36}, {0x641440, 0xc009df8700}, {0x0, 0x0})
        /home/jfcassan/Dev/immich-go/assets/files/localassets.go:73 +0x346
io/fs.walkDir({0x63dc20, 0xc0002865d0}, {0xc005f5f880, 0x36}, {0x641440, 0xc009df8700}, 0xc00bb11f80)
        /usr/local/go/src/io/fs/walk.go:73 +0x6c
io/fs.walkDir({0x63dc20, 0xc0002865d0}, {0xc0048786e0, 0x1e}, {0x641440, 0xc0000d7ce0}, 0xc00bb11f80)
        /usr/local/go/src/io/fs/walk.go:95 +0x2c5
io/fs.walkDir({0x63dc20, 0xc0002865d0}, {0xc005bdc0e0, 0xd}, {0x641440, 0xc0000d6150}, 0xc00bb11f80)
        /usr/local/go/src/io/fs/walk.go:95 +0x2c5
io/fs.walkDir({0x63dc20, 0xc0002865d0}, {0x6399e0, 0x1}, {0x6414e8, 0xc00403df80}, 0xc00bb11f80)
        /usr/local/go/src/io/fs/walk.go:95 +0x2c5
io/fs.WalkDir({0x63dc20, 0xc0002865d0}, {0x6399e0, 0x1}, 0xc000147f80)
        /usr/local/go/src/io/fs/walk.go:122 +0xd2
immich-go/assets/files.(*LocalAssetBrowser).Browse.func1({0x6412f0, 0xc00011a0a0})
        /home/jfcassan/Dev/immich-go/assets/files/localassets.go:37 +0xdf
created by immich-go/assets/files.(*LocalAssetBrowser).Browse in goroutine 1
        /home/jfcassan/Dev/immich-go/assets/files/localassets.go:35 +0xed
PS C:\Google Takeout>


Managing albums
245594 media scanned, 392 uploaded.
Done.
panic: runtime error: slice bounds out of range [32716:32707]

goroutine 50 [running]:
immich-go/immich/metadata.searchPattern({0xa7da40, 0xc00adb15c0}, {0xc00b99d854, 0x4, 0x4}, 0x3c)
        /home/jfcassan/Dev/immich-go/immich/metadata/search.go:42 +0x285
immich-go/immich/metadata.readMP4DateTaken({0xa7da40?, 0xc00adb15c0?})
        /home/jfcassan/Dev/immich-go/immich/metadata/direct.go:79 +0x45
immich-go/immich/metadata.GetFromReader({0xa7da40, 0xc00adb15c0}, {0xc00b170cb2, 0x4})
        /home/jfcassan/Dev/immich-go/immich/metadata/direct.go:44 +0x106
immich-go/assets/files.(*LocalAssetBrowser).ReadMetadataFromFile(0xc00b170c9f?, 0xc00af77ce0)
        /home/jfcassan/Dev/immich-go/assets/files/localassets.go:121 +0xa5
immich-go/assets/files.(*LocalAssetBrowser).Browse.func1.1({0xc00b170c80, 0x36}, {0xa81440, 0xc008aefd50}, {0x0, 0x0})
        /home/jfcassan/Dev/immich-go/assets/files/localassets.go:73 +0x346
io/fs.walkDir({0xa7dc20, 0xc00002a510}, {0xc00b170c80, 0x36}, {0xa81440, 0xc008aefd50}, 0xc00b99df80)
        /usr/local/go/src/io/fs/walk.go:73 +0x6c
io/fs.walkDir({0xa7dc20, 0xc00002a510}, {0xc00487f6a0, 0x1e}, {0xa81440, 0xc007256150}, 0xc00b99df80)
        /usr/local/go/src/io/fs/walk.go:95 +0x2c5
io/fs.walkDir({0xa7dc20, 0xc00002a510}, {0xc00724ac30, 0xd}, {0xa81440, 0xc0000d6150}, 0xc00b99df80)
        /usr/local/go/src/io/fs/walk.go:95 +0x2c5
io/fs.walkDir({0xa7dc20, 0xc00002a510}, {0xa799e0, 0x1}, {0xa814e8, 0xc00724e0a0}, 0xc00b99df80)
        /usr/local/go/src/io/fs/walk.go:95 +0x2c5
io/fs.WalkDir({0xa7dc20, 0xc00002a510}, {0xa799e0, 0x1}, 0xc0004b7f80)
        /usr/local/go/src/io/fs/walk.go:122 +0xd2
immich-go/assets/files.(*LocalAssetBrowser).Browse.func1({0xa812f0, 0xc00011a0a0})
        /home/jfcassan/Dev/immich-go/assets/files/localassets.go:37 +0xdf
created by immich-go/assets/files.(*LocalAssetBrowser).Browse in goroutine 1
        /home/jfcassan/Dev/immich-go/assets/files/localassets.go:35 +0xed
PS C:\Google Takeout>

**Comment by simulot** [comment]
oh gosh... Is it possible to share the file MVIMG_20181018_173636.MP4 ?

**Comment by simulot** [comment]
I have prepared a debug version that produce much more logs and with a possible correction of this problem
@BenSanborn, would you like test it?

**Comment by BenSanborn** [comment]
> I have prepared a debug version that produce much more logs and with a possible correction of this problem @BenSanborn, would you like test it?

Yes I would! I'll also see what that video is.

**Comment by BenSanborn** [comment]
I'd rather not distribute the video, it has my kids in it.

It's a portrait video that may have originated as a slo-mo video on my phone. I only say that because the resolution is super low. here are the video details in windows:

![image](https://github.com/simulot/immich-go/assets/8119804/cd519fde-6ced-4106-acba-f3814d30f1ab)

**Comment by simulot** [comment]
No problem. Can I send the debug version through discord?

**Comment by simulot** [comment]
fixed with release 0.8.3

**Comment by simulot** [comment]
Merge error

**Comment by simulot** [comment]
re-fixed
