### ISSUE TITLE
how to use immich-go

### ISSUE THREAD

**Issue by maserowik** [simulot/immich-go#72]
I download the zip form the git hub. I expanded the file on my windows machine.  I see I have to issues the ./immich-go from command prompt.  I do not see that file on the list of downloaded files.  Not sure I truely understand how to use this addon.

Mike

**Comment by simulot** [comment]
Be sure to have downloaded the latest binary release for windows from the release page https://github.com/simulot/immich-go/releases

Its a command line program. So you have to dezip the file, and run the exe file from this location. It requires a bunch of parameters like the server url, the API key, and the command and its parameter.

**Comment by maserowik** [comment]
I got it working thanks
