### ISSUE TITLE
Panic when upoload google photos

### ISSUE THREAD

**Issue by simulot** [simulot/immich-go#8]
This issue is focused on the panic reported on #3 by @dolfje :

```
Uploading "Takeout/Google Photos/Photos from 2015/IMG_20150726_231620_nopm_.jpg"...--- API CALL ---
POST https://***/api/asset/upload
X-Api-Key : ***
Accept : application/json
Content-Type : multipart/form-data; boundary=782650cc2469e7caf464607f742782639f2e4095b72160143516230df0e8
--- API RESPONSE -- 
Server Caddy,nginx/1.25.0
Content-Length 62
Accept-Ranges bytes
Content-Type application/json; charset=utf-8
Date Wed, 30 Aug 2023 18:28:22 GMT
Alt-Svc h3=":2283"; ma=2592000
Etag "3e-2GvAdOOIpCxCm7nPR7vOuJWs9CA"
X-Powered-By Express
--- RESPONSE BODY ---
{"id":"d5a216da-d6a9-42f4-858c-6e6e2ed17d3a","duplicate":true}
--- BODY ---
already exists on the server
Uploading "Takeout/Google Photos/Photos from 2015/IMG_20150812_213143_nopm_.jpg"...--- API CALL ---
POST https://***/api/asset/upload
Accept : application/json
Content-Type : multipart/form-data; boundary=9d63fa0ba517f7546fa9f8b4e070924b7c423b36f1c2360d9b23db2f086d
X-Api-Key : ***
--- API RESPONSE -- 
Accept-Ranges bytes
Alt-Svc h3=":2283"; ma=2592000
X-Powered-By Express
Content-Type application/json; charset=utf-8
Date Wed, 30 Aug 2023 18:28:22 GMT
Etag "3e-Synu08O9XRcnjW+GfWxvoZYNzRo"
Server Caddy,nginx/1.25.0
Content-Length 62
--- RESPONSE BODY ---
{"id":"365fec50-c4c1-4117-b23d-6cc103170c5d","duplicate":true}
--- BODY ---
already exists on the server
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7e58a7]

goroutine 1 [running]:
immich-go/cmdupload.(*AssetIndex).adviceSameOnServer(0x835d40?, 0xc0088bee00)
	/home/jfcassan/dev/github.com/simulot/immich-go/cmdupload/upload.go:507 +0x27
immich-go/cmdupload.(*AssetIndex).ShouldUpload(0xc000a6cc80, 0xc00544a3c0)
```

Possible problems are:
- The file name derived from the json file doesn't match the real files in the archive
- The coordinates are missing

**Comment by simulot** [comment]
the version https://github.com/simulot/immich-go/releases/tag/v0.1.7debug7 produce must less logs...

Another way to be focused on the problem is to handle only photos from a given date `-date=2015-07-26`.

```
./immich-go -server=http://localhost:2283 -key=XXXXXX -log-level=debug -no-colors-log -api-trace -log-level=debug upload -date=2015-07-26 -google-photos "~/takeout/full/*.zip" > log.log
```

**Comment by dolfje** [comment]
This is the output:

```
immich-go  dev, commit none, built at unknown
Server status: OK
Connected, user: nikos@uwsoftware.be
Get server's assets... 45319 received
Browsing google take out archive...
Browsing local assets for findings albums
13519 media scanned...
handleAsset: LocalAssetFile=:
{
 "FileName": "Takeout/Google Photos/Photos from 2015/IMG_20150726_231620_nopm_.jpg",
 "Title": "IMG_20150726_231620:nopm:.jpg",
 "Album": null,
 "Err": null,
 "SideCar": null,
 "DateTaken": "2015-07-26T23:16:20Z",
 "Latitude": 0,
 "Longitude": 0,
 "Altitude": 0,
 "Trashed": false,
 "Archived": false,
 "FromPartner": true,
 "MetadataFile": "Takeout/Google Photos/Photos from 2015/IMG_20150726_231620_nopm_.jpg.json",
 "FSys": null
}

IMG_20150726_231620:nopm:.jpg: This a new asset, upload it.
Uploading "Takeout/Google Photos/Photos from 2015/IMG_20150726_231620_nopm_.jpg"...already exists on the server
45187 media scanned...
Done.

```

**Comment by simulot** [comment]
I don't see any panic. The "IMG_20150726_231620_nopm_.jpg" exists already.
I have tested when there isn't any GPS coordinate, as yours. It works. 

I think the picture that triggers the panic has been filtered out.  Have you tried to run the import once again without filter?

**Comment by dolfje** [comment]
I though your changes in the application made it stop the panic. I did it again fully and got the following:

```
...
NHEcom002.jpg: This a new asset, upload it.
Uploading "Takeout/Google Photos/Eerste communie/NHEcom002.jpg"...already exists on the server
handleAsset: LocalAssetFile=:
{
 "FileName": "Takeout/Google Photos/Eerste communie/NHEcom003.jpg",
 "Title": "NHEcom003.jpg",
 "Album": [
  "Eerste communie"
 ],
 "Err": null,
 "SideCar": null,
 "DateTaken": "1996-06-02T08:00:00Z",
 "Latitude": 0,
 "Longitude": 0,
 "Altitude": 0,
 "Trashed": false,
 "Archived": false,
 "FromPartner": false,
 "MetadataFile": "Takeout/Google Photos/Eerste communie/NHEcom003.jpg.json",
 "FSys": null
}

1084 media scanned...panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7e5216]

goroutine 1 [running]:
immich-go/cmdupload.(*AssetIndex).ShouldUpload(0xc00070d720, 0xc0072f6600)
        /home/jfcassan/dev/github.com/simulot/immich-go/cmdupload/upload.go:582 +0x396
immich-go/cmdupload.(*UpCmd).handleAsset(0xc0000ec200, {0x95b958, 0xc0000cc370}, 0xc0072f6600)
        /home/jfcassan/dev/github.com/simulot/immich-go/cmdupload/upload.go:203 +0x485
immich-go/cmdupload.UploadCommand({0x95b958, 0xc0000cc370}, 0x8b0155?, 0x13?, {0xc0000be080?, 0x1?, 0x1?})
        /home/jfcassan/dev/github.com/simulot/immich-go/cmdupload/upload.go:132 +0xa2d
main.Run({0x95b958, 0xc0000cc370}, 0x1?)
        /home/jfcassan/dev/github.com/simulot/immich-go/main.go:122 +0xd3e
main.main()
        /home/jfcassan/dev/github.com/simulot/immich-go/main.go:44 +0x2a5

```

**Comment by simulot** [comment]
Me either!  Thanks to this, I have found the root cause. On the server, the picture date is empty, which is  mishandled. 

Here a the fix: https://github.com/simulot/immich-go/releases/tag/v0.1.7debug8


This means you have pictures in the server with no date. I good reason for this is that image's Exif data has been stripped by WhatsApp or so.

I'm working on an option to fix missing date when the date is in the file name like this IMG-20190204-WA0040.jpg or when the takeout json has the date.

**Comment by dolfje** [comment]
This issue has been resolved. I could do the import without any panics. But I have notices some other particularities, but maybe I should dedicate other issues on them when I have had more time to investigate.
1. Already created albums (with the same name) are not filled in with the photos from the archive
2. There is a difference between the number of photos inside the original google photos album and the immich album. Didn't investigate if this is just counting errors, difference in the counting way or really missing photos.

**Comment by simulot** [comment]
Thanks for the report. You can open another issue

**Comment by dolfje** [comment]
Never mind. Google takeout only downloads your own photo's, not the photo's others have added in your album. So that is the count difference...

So thank you for all changes!

**Comment by dolfje** [comment]
If you have any pointers on tools to download the shared albums with all their photos. Any information is welcome ;)

**Comment by simulot** [comment]
I haven't found  shared albums in takeout files.

Anyway, I have downloaded the album from the album page. The zip contains all photos from all contributors of the album.

I have imported  it as regular import (with the option -google-photos). The result is:
- new images have been updated
- already in immich images have been discarded

Not so bad, but the album is not created. 
I have to fix this, and you'll be able to add photos from any sources in your albums

**Comment by dolfje** [comment]
Nice.

I have used https://github.com/NicholasDawson/ArchiverForGooglePhotos to download all photo's for me.
As I had to many albums to do it manually.
I think the downside from that will be that the location and date will probably be wrong?

**Comment by simulot** [comment]
@dolfje I have fixed the -album options for non google takeout archive. v0.2.1
It now upload fresh images from the archive, and add them the album.
When the album wasn't exist, it creates the album, and populate it with fresh images and existing one.

This should address your problem.
