### ISSUE TITLE
unknown time zone Argentina/Buenos_Aires

### ISSUE THREAD

**Issue by simulot** [simulot/immich-go#86]

**Comment by gosoares** [comment]
i'm getting `unknown time zone NoDstSao_Paulo`.

**Comment by simulot** [comment]
What is you os? 
You can force the time zone with an option on the command line:

```
./immich-go -server=http://mynas:2283 -key=xxxxx -time-zone=America/Sao_Paulo upload
-create-albums -google-photos .path/to/takeout-*.zip    
```

**Comment by gosoares** [comment]
The OS was ADM (linux-based, for asustor nas).
Setting the time-zone in the command worked fine, thank you.

**Comment by simulot** [comment]
Thx, let's close this
