### ISSUE TITLE
*.jpeg are not recognized

### ISSUE THREAD

**Issue by zakul** [simulot/immich-go#9]
Hi there!

First of all thank you for creating this tool. It has been a pleasure to use while importing photos from Google.
Now, this time I created an export from my Mac photo library and all the videos have been uploaded, but the photos have been exported as *.jpeg and are being ignored. 

The only difference I noticed between my previous upload and this one is that Google is using the *.jpg ending, could that be the issue?

**Comment by simulot** [comment]
Thank for using the program  and reporting issues.

Indeed, you're right.
I have fixed this issed in the version 0.1.8

**Comment by simulot** [comment]
> Now, this time I created an export from my Mac photo library and all the videos have been uploaded, but the photos have been exported as *.jpeg and are being ignored.

Are you running immich-go on a mac?

**Comment by zakul** [comment]
Yes, I am using it on a Mac.

**Comment by simulot** [comment]
I was hoping it was working on a Mac, but until now I didn't have any evidence of it. Thank you for using the program.

**Comment by zakul** [comment]
Happy to answer any questions.
