### ISSUE TITLE
Managing Whatsapp photos

### ISSUE THREAD

**Issue by gmag11** [simulot/immich-go#92]
When uploading files, Whatsapp photo and video assets have no metadata. Date indication is just only in the filename. Could a filter be added so that a file with name IMG-YYYYMMDD-WAxxxx.jpg is added with data YYYY-MM-DD?

**Comment by simulot** [comment]
1/ You can give a filter in the command line 
./immich-go -server... -key.... upload ~/Download/whatsapp/IMG-2023*.*

2/ You can use the [date range option](https://github.com/simulot/immich-go/tree/main#date-selection).
./immich-go -server... -key.... upload  -date 2023-10-01 ~/Download/whatsapp

I haven't tested it specially. But I think it can work. immich-go tries to find the capture date using various ways:
- google json with -google-photos option
- the file name (your file should work)
- the exif/mp4 date

**Comment by gmag11** [comment]
I will test it. Thanks!
