### ISSUE TITLE
stack: for Pixel 5 and Pixel 8 Pro naming schemes

### ISSUE THREAD

**Issue by townsste** [simulot/immich-go#94]
Below are the naming schemes I get when taking photos with Pixel 5 and Pixel 8 Pro

Google Pixel 5
Normal - STACKS
PXL_20231026_210642603.dng
PXL_20231026_210642603.jpg

Burst - DOES NOT STACK
PXL_20231026_205755225.dng
PXL_20231026_205755225.MP.jpg

Google Pixel 8 Pro
Normal - DOES NOT STACK
PXL_20231207_032111247.RAW-02.ORIGINAL.dng
PXL_20231207_032111247.RAW-01.COVER.jpg

Burst - DOES NOT STACK
PXL_20231207_032108788.RAW-02.ORIGINAL.dng
PXL_20231207_032108788.RAW-01.MP.COVER.jpg

**Comment by simulot** [comment]
Thanks, I'll check those.
