### ISSUE TITLE
FRQ: Support tgz takeout files

### ISSUE THREAD

**Issue by jonathanjsimon** [simulot/immich-go#96]
My takeout export is enormous so I export in 50GB tgz files because downloading 300 2GB zip files would be hilariously unfun. Any chance for tgz file support?

**Comment by simulot** [comment]
I'm not sure about your math ;-)
Anyway you will find a long discussion #36 on the support of tgz files.

In short: not a the moment because there are some easy workarounds. But, I have some ideas for doing it.

**Comment by jonathanjsimon** [comment]
Well, my export is 600+GB so...it's 12+ 50GB tgz files or 300+ 2GB zip files.

But I'll check the other report. I'd searched for tar and tgz before making a new request. Not sure why that didn't come up.

Thanks!
