### ISSUE TITLE
stack: Samsung

### ISSUE THREAD

**Issue by krystiancharubin** [simulot/immich-go#99]
Burst - Not Stacking
```
20231207_101605_001.jpg
...
20231207_101605_039.jpg
```

Regular
```
20231207_101552.jpg
20231206_161514.jpg
20231204_094932.jpg
```

**Comment by simulot** [comment]
Thanks for using the project.
How the cover image is determined? Is it always the photo 001?

**Comment by krystiancharubin** [comment]
In this instance picture 010 was picked as the cover but there is nothing in filenames that would indicate that.
I would be happy enough if we just pick 001 as the cover.
